### ISSUE TITLE
Build error (grammars/whitespace_grammar_inst.cpp: No such file or directory)

### ISSUE THREAD

**Issue by linsson** [stan-dev/pystan2#129]
Hi all!

I receive the following error when trying "python setup.py install":

Compiling pystan/_api.pyx because it changed.
Compiling pystan/_chains.pyx because it changed.
Compiling pystan/_misc.pyx because it changed.
Cythonizing pystan/_api.pyx
Cythonizing pystan/_chains.pyx
Cythonizing pystan/_misc.pyx
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pystan
copying pystan/model.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/_compat.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/misc.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/plots.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/constants.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/chains.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/api.py -> build/lib.linux-x86_64-2.7/pystan
copying pystan/__init__.py -> build/lib.linux-x86_64-2.7/pystan
creating build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_stan_args.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_optimizing_example.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_basic.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_pickle.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_basic_matrix.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_test8schools2.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_linear_regression.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_stan_file_io.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_chains.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_zerolen.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_stanc.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_misc.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_extract.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_testoptim.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_getting_started.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_stanfit.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_basic_array.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_test8schools.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_parallel.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_basic_pars.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/**init**.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_rstan_testfixp.py -> build/lib.linux-x86_64-2.7/pystan/tests
copying pystan/tests/test_user_inits.py -> build/lib.linux-x86_64-2.7/pystan/tests
creating build/lib.linux-x86_64-2.7/pystan/external
copying pystan/external/**init**.py -> build/lib.linux-x86_64-2.7/pystan/external
creating build/lib.linux-x86_64-2.7/pystan/external/pymc
copying pystan/external/pymc/stats.py -> build/lib.linux-x86_64-2.7/pystan/external/pymc
copying pystan/external/pymc/plots.py -> build/lib.linux-x86_64-2.7/pystan/external/pymc
copying pystan/external/pymc/**init**.py -> build/lib.linux-x86_64-2.7/pystan/external/pymc
copying pystan/external/pymc/trace.py -> build/lib.linux-x86_64-2.7/pystan/external/pymc
creating build/lib.linux-x86_64-2.7/pystan/external/enum
copying pystan/external/enum/test_enum.py -> build/lib.linux-x86_64-2.7/pystan/external/enum
copying pystan/external/enum/enum.py -> build/lib.linux-x86_64-2.7/pystan/external/enum
copying pystan/external/enum/**init**.py -> build/lib.linux-x86_64-2.7/pystan/external/enum
creating build/lib.linux-x86_64-2.7/pystan/external/scipy
copying pystan/external/scipy/**init**.py -> build/lib.linux-x86_64-2.7/pystan/external/scipy
copying pystan/external/scipy/mstats.py -> build/lib.linux-x86_64-2.7/pystan/external/scipy
copying pystan/pystan_recorder.hpp -> build/lib.linux-x86_64-2.7/pystan
copying pystan/stanc.hpp -> build/lib.linux-x86_64-2.7/pystan
copying pystan/stan_fit.hpp -> build/lib.linux-x86_64-2.7/pystan
copying pystan/py_var_context.hpp -> build/lib.linux-x86_64-2.7/pystan
copying pystan/py_var_context_factory.hpp -> build/lib.linux-x86_64-2.7/pystan
copying pystan/io.pxd -> build/lib.linux-x86_64-2.7/pystan
copying pystan/stan_fit.pxd -> build/lib.linux-x86_64-2.7/pystan
copying pystan/stanc.pxd -> build/lib.linux-x86_64-2.7/pystan
copying pystan/_chains.pyx -> build/lib.linux-x86_64-2.7/pystan
copying pystan/_api.pyx -> build/lib.linux-x86_64-2.7/pystan
copying pystan/stanfit4model.pyx -> build/lib.linux-x86_64-2.7/pystan
copying pystan/_misc.pyx -> build/lib.linux-x86_64-2.7/pystan
creating build/lib.linux-x86_64-2.7/pystan/tests/data
copying pystan/tests/data/blocker2.csv -> build/lib.linux-x86_64-2.7/pystan/tests/data
copying pystan/tests/data/blocker1.csv -> build/lib.linux-x86_64-2.7/pystan/tests/data
running build_ext
building 'pystan._api' extension
C compiler: /usr/local/gcc/4.8.3//gcc/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -march=native -mtune=native -O2 -pipe -fPIC -march=native -mtune=native -O2 -pipe -fPIC

creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pystan
creating build/temp.linux-x86_64-2.7/pystan/stan
creating build/temp.linux-x86_64-2.7/pystan/stan/src
creating build/temp.linux-x86_64-2.7/pystan/stan/src/stan
creating build/temp.linux-x86_64-2.7/pystan/stan/src/stan/gm
creating build/temp.linux-x86_64-2.7/pystan/stan/src/stan/gm/grammars
compile options: '-DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -Ipystan/stan/src -Ipystan/stan/lib/eigen_3.2.0 -Ipystan/stan/lib/boost_1.54.0 -I/usr/local/gcc/4.8.3/python/2.7.8/include/python2.7 -c'
extra options: '-O0 -ftemplate-depth-256'
gcc: pystan/stan/src/stan/gm/grammars/whitespace_grammar_inst.cpp
gcc: error: pystan/stan/src/stan/gm/grammars/whitespace_grammar_inst.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: pystan/stan/src/stan/gm/grammars/whitespace_grammar_inst.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: Command "/usr/local/gcc/4.8.3//gcc/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -march=native -mtune=native -O2 -pipe -fPIC -march=native -mtune=native -O2 -pipe -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -Ipystan/stan/src -Ipystan/stan/lib/eigen_3.2.0 -Ipystan/stan/lib/boost_1.54.0 -I/usr/local/gcc/4.8.3/python/2.7.8/include/python2.7 -c pystan/stan/src/stan/gm/grammars/whitespace_grammar_inst.cpp -o build/temp.linux-x86_64-2.7/pystan/stan/src/stan/gm/grammars/whitespace_grammar_inst.o -O0 -ftemplate-depth-256" failed with exit status 1

As you can see I am using

gcc v. 4.8.
python v. 2.7.8
pystan v. 2.5.0.1

I also have my own boost installation (v 1.57.0) and eigen (v 3.0.5) but I don't know how to make the build process aware of it. Anyhow the error seems to be related to a missing file in src (whitespace_grammar_inst.cpp). Could you please help me?

Thanks in advance!

**Comment by fx86** [comment]
> I'm not sure how to handle this. The documentation needs to be updated in any event. Essentially, you need to do a `git clone --recursive https://github.com/stan-dev/pystan.git`; you can't use the releases.

I wish there was a way to upvote this 10 times. I could make pystan compile a model only after compiling from source code.

**Comment by bob-carpenter** [comment]
Why create releases on GitHub if they're not official releases?   That's going to continue to be super confusing for GitHub users.

If for some reason you think you need to create releases that people can't use as actual releases, you might want to salt a dummy release between each actual non-release with an all-caps warning to not download releases from here.

The GitHub releases *are* official releases for the Math Library, Stan, and CmdStan.  That's the only way we distribute them (other than by git cloning or forking).  I think the releases for RStan are real, too, and I believe they can be installed through GitHub as well as through CRAN, but I'm not 100% sure.  Is that right @bgoodri?
