### ISSUE TITLE
PyStan broken on IPython Notebook + qtconsole ('OutStream' error)

### ISSUE THREAD

**Issue by sjobeek** [stan-dev/pystan2#3]
Running into the following error on Windows (32 bit Anaconda installation) when I attempt to run the example:

```
AttributeError: 'OutStream' object has no attribute 'fileno'
```

I read that this issue can be related to the IPython Notebook and how it uses /over-writes the stderr

See what looked to be a similar issue several months ago in SciPy: 
https://github.com/ipython/ipython/issues/3017

I can confirm that this issue happens in the IPython Notebook and the qtconsole. The same code is tested and working fine from the terminal. 

Since the IPython notebook is so popular, this is definitely one to fix!

Thanks for implementing PyStan, though! This is going to be quite useful =)

```
WARNING:root:COMPILING THE C++ CODE FOR MODEL anon_model NOW.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-f3d4d4964bda> in <module>()
      1 fit = pystan.stan(model_code=schools_code, data=schools_dat,
----> 2                   iter=1000, chains=4)

C:\Anaconda\lib\site-packages\pystan\api.pyc in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, sample_file, diagnostic_file, save_dso, verbose, boost_lib, eigen_lib, **kwargs)
    246         m = StanModel(file=file, model_name=model_name, model_code=model_code,
    247                       boost_lib=boost_lib, eigen_lib=eigen_lib,
--> 248                       save_dso=save_dso, verbose=verbose, **kwargs)
    249     if sample_file is not None:
    250         raise NotImplementedError

C:\Anaconda\lib\site-packages\pystan\model.pyc in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, save_dso, verbose, **kwargs)
    258         if not verbose:
    259             # silence stderr for compilation
--> 260             orig_stderr = pystan.misc.redirect_stderr()
    261 
    262         build_extension.run()

C:\Anaconda\lib\site-packages\pystan\misc.py in redirect_stderr()
    438     """
    439     sys.stderr.flush()
--> 440     stderr_fileno = sys.stderr.fileno()
    441     orig_stderr = os.dup(stderr_fileno)
    442     devnull = os.open(os.devnull, os.O_WRONLY)

AttributeError: 'OutStream' object has no attribute 'fileno'

```

**Comment by JanSchulz** [comment]
@dougalsutherland the sollution in #4 should also check for `IOErrors`: https://docs.python.org/2/library/io.html#io.IOBase.fileno

**Comment by ariddell** [comment]
@JanSchulz Is there a change needed in PyStan? Should a new issue be opened?

**Comment by dougalsutherland** [comment]
@ariddell This seems right to me, though in practice it probably doesn't happen. Just added a PR (#144).

**Comment by khgitting** [comment]
I've been having this problem as well though not to the same degree--I can fit at least one model when in a notebook, but when fitting multiple models in one notebook, I hit this same hanging issue. python 2.7.8 and ipython 2.1.0.

To not disrupt my notebook workflow, I have an ugly kludge that runs a new process and writes traces to file. Posting here in case anyone is searching for a quick and dirty workaround. ymmv, and please excuse any uncleanliness in the code:

```
def run_stan_in_new_process(model, data, trace_base, init_dict=None, iter=1000, chains=4):
    """
    Kludge that prevents hanging errors which occur when running multiple models in a notebook
    by running in a separate process and writing traces to file.
    (Notebooks are struggling with pystan, google says)
    """
    with open('tmp_data.p', 'w') as f:
        pickle.dump(data, f)
    with open('tmp_model.p', 'w') as f:
        pickle.dump(model, f)
        
    init = False
    if init_dict is not None:
        with open('tmp_init_dict.p', 'w') as f:
            pickle.dump(init_dict, f)
        init = True
    script = """
import pystan
import pickle
init = {}
with open('tmp_data.p', 'r') as f:
    data = pickle.load(f)
with open('tmp_model.p', 'r') as f:
    model = pickle.load(f)

def get_init_dict():
    with open('tmp_init_dict.p', 'r') as f:
        init_dict = pickle.load(f)
    return init_dict
    
if init:
    init = get_init_dict
else:
    init = None

pystan.stan(model_code=model, data=data, iter={}, chains={}, sample_file='{}', init=init)
             """.format(init, iter, chains, trace_base)
    with open('tmp_script.py', 'w') as f:
        f.write(script)
    os.system('python tmp_script.py')
```

**Comment by ariddell** [comment]
@khgitting Is this a separate problem? Or is it related to the "OutStream" error? Should there be a new issue to track this?

It seems like adding a test that covers the IPython notebook case might be a good idea. I wonder if there's another project that's already doing this on travis-ci.

**Comment by khgitting** [comment]
Ope, you are right, this is not related to the OutStream error.

After further poking around, I'm not sure the problem I reference is pystan related or if it is just ipython memory management. If it is revealed that it is pystan, I will open a separate issue to track.
