### ISSUE TITLE
Check code style of pull requests automatically

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan2#338]
A minimal set of coding conventions (PEP8 + Google Style) should be checked automatically. Things like:
- 4 space indents
- 120 line max
- no unused variables
- snake_case, capitalized class names
- alphabetic imports

I hope this is not difficult to setup. If anyone has some examples of this in the wild (esp if using travis), please speak up.

**Comment by betanalpha** [comment]
We do this in math, stan, and cmdstan with cpplint which works great.

**Comment by mkcor** [comment]
Hi @ariddell,

I would suggest using `flake8` (a tool combining `pep8` and `pyflakes`). I'm familiar with it thanks to the `yt` project (see https://github.com/yt-project/yt/blob/master/CONTRIBUTING.rst#automatically-checking-code-style). We can configure which PEP8 errors and warnings we want to detect vs ignore.

I'm happy to work on a pull request, but I would need some guidance to overcome this: https://github.com/stan-dev/pystan/blob/ea186baac916dc0f9fbf56ffa92a51f521831587/.travis.yml#L3 I would be a lot more comfortable if it said `language: python`!

Best,
Marianne

PS: Looping in @jgabry.

**Comment by ariddell** [comment]
Great point. flake8 is wonderful. We should figure out a way to run it.
I wonder if we can run it in such a way that it only tests new code. I'm
sure the existing codebase is not entirely compliant with all of
flake8's checks.

As for flake8 options, I tend to use: ``--ignore=H238,H304
--max-line-length=120 --max-complexity=12`` (H238,H304 do not apply to
Python 3, IIRC)

**Comment by mkcor** [comment]
Indeed, there are many flake8 violations in the current codebase:
```
marianne@...:~/python/pystan(develop)$ python3.6 -m flake8 --max-line-length=120 --max-complexity=12 | wc -l
2164
```
So we probably want to check only new code, which calls for [flake8 --diff](http://flake8.readthedocs.io/en/latest/user/options.html#cmdoption-flake8-diff).

We could do something along the lines of https://github.com/scikit-learn/scikit-learn/pull/7127; what do you think?

Additionally, we should tell contributors (in the contribution guidelines) about `flake8 --diff` and/or the Git [pre-commit](https://consideratecode.com/2016/10/15/check-code-changes-with-flake8-before-committing/) hook.

**Comment by ariddell** [comment]
@mkcor Sounds like a plan.

If you, or anyone else, is interested in testing things out it might be easiest to start with stan-dev/pystan-next because the tests will finish about 10x faster.

**Comment by mkcor** [comment]
Great! I have forked stan-dev/pystan-next and opened an issue, as you can see.

@ariddell @bob-carpenter @jgabry By the way, I would like to suggest that we use `master` as the base branch in stan-dev/pystan-next (as opposed to `develop` in stan-dev/pystan), so that we mesh better with the SciPy ecosystem.

**Comment by mkcor** [comment]
@ariddell Thank you for drawing my attention to stan-dev/httpstan. I wonder where it fits exactly in this picture https://github.com/stan-dev/stan/wiki/Where-do-I-create-a-new-issue#overview (I guess, close to `cmdstan`)... @jgabry

Indeed, it looks like httpstan's CI supports style checking with flake8, but I thought you wanted to focus on style checking for new/submitted code *only*; so we still have to go through the 'trouble' of calling `flake8 --diff` and more complex machinery... Right?

**Comment by ariddell** [comment]
There's some background that I should mention. Both RStan and PyStan are
inching towards new user-facing APIs (dubbed RStan 3 and PyStan 3). The
version of PyStan living inside of pystan-next (and its dependency,
httpstan) is the prototype of PyStan 3.

I've enabled (or will enable shortly) mypy and flake8 checking on this
new thing (both pystan-next and httpstan). My initial plan was to forget
about flake8 on the old pystan and just focus on PyStan 3.

Adding incremental flake8 checking to PyStan 2 would be valuable of course.

I suppose there are separate issues here. PyStan 2 (stan-dev/pystan)
needs incremental checking if it needs any checking at all. PyStan 3
(stan-dev/pystan-next) needs to be checked to see if it's doing the mypy
and flake8 checks correctly (once I add .travis.yml).
