### ISSUE TITLE
Change (slightly) how user-provided inits are provided in sampling

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan2#383]
#### Summary:

This concerns accepted values for the ``init`` argument in sampling.

A function which returns user-specified initial values should take one argument, the chain id. It can be ignored by the user but it is not "optional."

#### Description:

I believe there is an R-ism present in how the ``init`` argument is handled. Here are the values it can take when the user is providing initial values explicitly:

    list of size equal to the number of chains (chains), where the
        list contains a dict with initial parameter values;

    function returning a dict with initial parameter values. The
        function may take an optional argument chain_id.

The second one is the one I'm concerned with. "optional argument" is underspecified in Python. Is it a kwarg? Is it a normal argument? What would feel more natural to me in Python is that the function always receives the chain_id. (The user is, of course, free to ignore the chain id with something like ``lambda _: {'alpha': 3.0}``.)

(I say this is an R-ism because R has this ``missing()`` function which lets you identify after the fact which arguments were not provided. Python doesn't do this; it has kwargs with explicit default values.)

**Comment by bob-carpenter** [comment]
The R interface lets you use functions of two different signatures, `list init()` and `list init(int)`.  I'm not sure how that's implemented.  I like requiring the second form.  One of the things I always ask myself in making these decisions is which alternative is easier to document (and hence easier for users to understand)?

**Comment by ahartikainen** [comment]
Is this not the default way to handle optional arguments

```
def myinits(chain_id=None):
    if chain_id is None:
        do.stuff...
    ...
```

And for kwargs only (py3x+, don't remember when this option came)

```
def myinits(*, chain_id=None):
    if chain_id is None:
        do.stuff...
    ...
```

**Comment by riddell-stan** [comment]
I ran into this again recently. The function argument is confusing. @ahartikainen  would you object to dropping it as an option in PyStan 3 for now? It seems relatively easy for people to construct the appropriate inits list in advance. You only need one per chain and in Python making duplicate copies of a list of options is so easy: ``[{"theta": 3}] * 4``.

Relevant issue for PyStan 3 is https://github.com/stan-dev/pystan-next/issues/78

**Comment by ahartikainen** [comment]
Sounds fine by me. I have never used the function style.

So list len must match chain count?

If dict is given, should all chains start with it?

**Comment by ariddell** [comment]
I think explicit is better than implicit for now (and, of course, in 
general). We can put the "* trick" in the documentation for the users 
who aren't aware of it.

(I'm thinking we'll just change this in PyStan 3 since people are 
expecting API breakage.)

**Comment by ahartikainen** [comment]
So only lists (and tuples?) with the size of chain?

Sounds good to me.
