### ISSUE TITLE
Docs example using to_dataframe()

### ISSUE THREAD

**Issue by braaannigan** [stan-dev/pystan2#436]
I think that the ```to_dataframe()``` method in #425 will be the easiest way to access samples once it's merged.  I want to add some documentation showing how it works.  I was planning on doing a simple linear regression example - does anyone have an objection or any comments before I start?

**Comment by ahartikainen** [comment]
Sounds good.

Are you considering to manipulate the dataframe after the export? (E.g. adding x as index)

**Comment by ahartikainen** [comment]
Fyi notice #444 and issue #443

**Comment by braaannigan** [comment]
Thinking about this a bit more, I'd prefer just to use simulated data as it avoids issues with keeping links up-to-date etc.

**Comment by ahartikainen** [comment]
I don't see a problem if we use some external data.

One reason for this is that I always find it really confusing when I see examples of using simulated data (as their only datasource). It is missing the step where one is trying to guess the real model.

In my mind an example of fitting a model goes like this (option 1):

Real data --> plot it --> think about the model which created the data --> create a model and sample from it --> compare simulated data and real data (this is the step where one usually notices that things are not iid) --> update model (loop until satisfyid) --> fit parameters for simulated model --> check it works --> fit parameters for real data --> describe findings and update model if needed (loop).

And normally they are (option 2):

fit model to data --> print fit --> stop.

**Comment by tommylees112** [comment]
Has this been merged to the current working version or only in the dev version? Great functionality thanks guys!

**Comment by braaannigan** [comment]
Hi - it's in neither unfortunately, life intervened when I had barely got started. I don't expect to be able to work on anything before next summer due to continued life interventions!

**Comment by ahartikainen** [comment]
Is currently on the dev and next version 2.18 will be released in a day or two.
