### ISSUE TITLE
Stan throws error with empty array

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/pystan2#437]
_From @lazypanda1 on February 14, 2018 22:3_

When I run the example below with N = 0, I run into an error (also below). 

This error doesn't occur when `data` is empty but of type `real`, or when the `data` has at least one element (for both `real` and `int` types). The error message here is also unclear to me. `data` array is empty, it doesn't have `non-int` values. If array emptiness is an issue, why doesn't the program also fail for an empty `real` array?

Are all these expected?

```
data {
int<lower=0> N;
int datax[N];
}

model {
for(i in 1:N){
datax[i] ~ weibull(1.0,1.0);
}
}
```
Error message:
```bash
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_b792a2a57df879a15a969a03d556f524 NOW.
Traceback (most recent call last):
  File "driver.py", line 34, in <module>
    fit = sm.sampling(data=data, iter=1000, chains=4)
  File "/usr/local/lib/python2.7/dist-packages/pystan/model.py", line 671, in sampling
    fit = self.fit_class(data)
  File "stanfit4anon_model_b792a2a57df879a15a969a03d556f524_9077231157931774679.pyx", line 457, in stanfit4anon_model_b792a2a57df879a15a969a03d556f524_9077231157931774679.StanFit4Model.__cinit__
RuntimeError: int variable contained non-int values; processing stage=data initialization; variable name=data; base type=int
```
Environment
```
pystan 2.16.0.0
python 2.7.6
```

_Copied from original issue: stan-dev/stan#2468_

**Comment by bob-carpenter** [comment]
This is not a Stan issue, it's a PyStan issue.  I verified everything works fine in RStan with

```
data {
  int<lower = 0> N;
  int y[N];
}
model {
  for(n in 1:N)
    y[n] ~ weibull(1.0, 1.0);
}
```

with

```
stan("foo.stan", data = list(N = 0, y = array(0, dim=c(0))),
     algorithm="Fixed_param")
```
So I'm going to move this issue to the PyStan tracker.

**Comment by ahartikainen** [comment]
How is the data inserted to StanModel?

**Comment by lazypanda1** [comment]
I am loading the data from a json file, having the data as shown below:
```
{"datax": [], "N": 0}
```

Python code snippet:
```python
with open('data.json') as dataFile:
    data = json.load(dataFile)
...

fit = sm.sampling(data=data, iter=1000, chains=4)
```

**Comment by ahartikainen** [comment]
Ok. I know what is the problem:

    {'datax' : np.array([], int), 'N' : 0}

The reason for this is that the `np.asarray([])` has `float` as a default dtype.

See pystan.misc

    def _split_data(data):
        data_r = {}
        data_i = {}
        # data_r and data_i are going to be converted into C++ objects of
        # type: map<string, pair<vector<double>, vector<size_t>>> and
        # map<string, pair<vector<int>, vector<size_t>>> so prepare
        # them accordingly.
        for k, v in data.items():
            if np.issubdtype(np.asarray(v).dtype, np.integer):
                data_i.update({k.encode('utf-8'): np.asarray(v, dtype=int)})
            elif np.issubdtype(np.asarray(v).dtype, np.floating):
                 data_r.update({k.encode('utf-8'): np.asarray(v, dtype=float)})
            else:
                msg = "Variable {} is neither int nor float nor list/array thereof"
                raise ValueError(msg.format(k))
        return data_r, data_i

**Comment by ahartikainen** [comment]
Thinking about this, we probably don't want to parse dtypes from the stan model and can't change the defaults for numpy, so we could give a warning about the empty list being transformed to float and tell the user how to explicitly insert int array.

@ariddell any thoughts?

**Comment by bob-carpenter** [comment]
This has also been an ongoing problem with RStan.  The underlying cause is the same---dynamic types making it unconventional to specify the type of something that's empty.

**Comment by ariddell** [comment]
Two options. Either one would work.

1. What about a hideous hack and just try both (int and float)?
2. Doesn't Stan give us a way to get the types from a compiled model? If
not, what about adding that?

**Comment by ahartikainen** [comment]
If we can extract the dtypes, we could use them in `fit.extract` to automatically set the correct dtype. So do we need to change `fit.sim` to have `dtypes`-list or something similar.

**Comment by riddell-stan** [comment]
This relates to an important desirable: we need to be able to get the data types from the stan model. This is needed for a lot of things.

@bob-carpenter Can we get the data types for variables from a stan_model yet? I don't see it in an older but post-2.17 stan.

**Comment by ahartikainen** [comment]
I did something "similar" in ArviZ. It will return all `int` params. Everything else is `float`.
This will also include all local variables defined in `generated quantities` block, which is probably fine in most cases (is this even possible: `(int theta; ...); real theta`). 

It would be better if stan would return also dtypes for all returned variables.

https://github.com/arviz-devs/arviz/blob/master/arviz/utils/xarray_utils.py

```
def infer_dtypes(self):
        pattern_remove_comments = re.compile(
            r'//.*?$|/\*.*?\*/|\'(?:\\.|[^\\\'])*\'|"(?:\\.|[^\\"])*"',
            re.DOTALL|re.MULTILINE
        )
        stan_integer = r"int"
        stan_limits = r"(?:\<[^\>]+\>)*" # ignore group: 0 or more <....>
        stan_param = r"([^;=\s\[]+)" # capture group: ends= ";", "=", "[" or whitespace
        stan_ws = r"\s*" # 0 or more whitespace
        pattern_int = re.compile(
            "".join((stan_integer, stan_ws, stan_limits, stan_ws, stan_param)),
            re.IGNORECASE
        )
        stan_code = self.obj.get_stancode()
        # remove deprecated comments
        stan_code = "\n".join(\
                line if "#" not in line else line[:line.find("#")]\
                for line in stan_code.splitlines())
        stan_code = re.sub(pattern_remove_comments, "", stan_code)
        stan_code = stan_code.split("generated quantities")[-1]
        dtypes = re.findall(pattern_int, stan_code)
        dtypes = {item.strip() : 'int' for item in dtypes if item.strip() in self.varnames}
        return dtypes
```

**Comment by ahartikainen** [comment]
Also, this will fail with all the `#include` statements.

**Comment by ahartikainen** [comment]
I believe we can't fix this in 2.18? We could throw a warning when we see an empty list/tuple?

**Comment by riddell-stan** [comment]
@bob-carpenter when will we be able to introspect a stan model and get out the type (int or real) for a variable?

@ahartikainen I suppose we could warn if we see (1) an empty list *and* a scalar 0 in the data `dict`. A decent short-term fix, right?

**Comment by bob-carpenter** [comment]
Proper type introspection may be as much as nine to twelve months away.  We're going to stage recreating the current model class first in the new parser, then refactor to a base class.  The base class design will support retrieving more of the type information for variables.  There's also the issue of which blocks we need this for (data, t data, params, t params, gqs).

There are many more distinctions than int or real, and also constraints.  We can get the shapes and core constrained statically (e.g, 2-dimensional array of real, covariance matrix), the sizes when data is loaded, and constraint bounds only relative to specific parameter values (because we can use parameters as bounds in parameters defined later, such as real a; real<lower = a> b;).
