### ISSUE TITLE
Remove experimental whitespace fixer when resolved in Stan

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan2#477]
Reminder to clean up code once whitespace fix is in Stan (2.19?).

See https://github.com/stan-dev/pystan/pull/448#issuecomment-405151255

**Comment by bob-carpenter** [comment]
2.18 is already out for math, stan, and cmdstan.

But if you're talking about whitespace before # comments, that'll be fixed as soon as I get a second to code.  Probably in a day or two.
