### ISSUE TITLE
extract with permuted=True  unpacking in wrong order

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan2#501]
`fit.extract(permuted=False)` returns a numpy array.

one draw is get with  `draw=fit.extract(permuted=False)[-1, 0, :-1]` and corresponding `lp__` --> `lp=fit.extract(permuted=False)[-1, 0, -1]`.

One should have `fit.log_prob(draw) == lp`, but if there are matrices the order of unpacking is wrong. 

This can be seen with the same data but done by 
```
draw=fit.extract(pars=fit.model_pars+['lp__'], permuted=False)
lp = {key : values[-1, 0] for key, values in draw.items() if key == 'lp__'}['lp__']
draw = {key : values[-1, 0] for key, values in draw.items() if key != 'lp__'}
draw = fit.unconstrain_pars(draw)
fit.log_prob(draw) == lp # True
```

It is doing `order='F'` at some point when doing reshape/ravel, but should do `order='C'`.

**Comment by riddell-stan** [comment]
Interesting! I'm surprised this gets through given how much testing we have in ``test_basic_matrix.py``.

**Comment by riddell-stan** [comment]
@ahartikainen should we wait on releasing 2.18 for this? (I haven't looked into it seriously yet.) Otherwise I'll release today.

**Comment by ahartikainen** [comment]
I think we can release.

I believe anyone using it will do the transform manually and have tested it works. It is just an incompatibility between permured=True and log_prob.

**Comment by ahartikainen** [comment]
And before we change anything like this we probably should give a futureWarning that we are going to do it.
