### ISSUE TITLE
CI: simplify appveyor and add macOS tests

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan2#512]
appveyor tests are timing out. And we don't test macOS in this repository. Let's fix both of these problems. Let's pick one or two tests (ones that exercise Eigen) and have osx and appveyor run just those tests. It will slow down testing a bit but it's already very slow.

**Comment by ahartikainen** [comment]
Here are running times for invidual tests runned on windows

https://gist.github.com/ahartikainen/9589dedcb2045c556359814313742e13

**Comment by ahartikainen** [comment]
I reduced windows test so running time for each build is 30-40 minutes.

Still need to add tests for osx.
