### ISSUE TITLE
Feature request: option to suppress stan output (optimizing)

### ISSUE THREAD

**Issue by smoh** [stan-dev/pystan2#528]
#### Summary:
Currently there is no easy way to suppress the output from stan when calling e.g., `StanModel.optimizing` which prints progress of optimization.
It would be nice to be able to suppress it from pystan.

I feel like this might have come up already here. I found relevant discussions e.g., [here](https://github.com/facebook/prophet/issues/170) and [here](https://github.com/facebook/prophet/issues/223) but surprisingly with no ping back to pystan. If this is a duplicate, feel free to close.

I think this is also worth noting in the documentation somewhere..

#### PyStan Version:
2.18.0.0
#### Python Version:
3.7.0
#### Operating System:
mac os x 10.14

**Comment by bob-carpenter** [comment]
Thanks for raising the issue.  This is also a problem in RStan and probably in CmdStan.

This is something we're addressing more carefully in Stan 3 with logger levels.

As is, the interfaces have enough power to turn off all the output---they're just providing callbacks with output streams in them---those streams don't have to be standard output or standard error.  They can just be sinks.
