### ISSUE TITLE
pystan.stan memory overload when customizing the "control" parameter

### ISSUE THREAD

**Issue by mdastro** [stan-dev/pystan2#537]
#### Summary:
The same code consumes CPU memory very differently when ignoring or adding the "control" field.

#### Description:
I'm running a code that shows some warnings such as:

> WARNING:pystan:21 of 29100 iterations ended with a divergence (0%).
> WARNING:pystan:Try running with adapt_delta larger than 0.8 to remove the divergences.

It takes this code ~ 11 minutes to run.

So, I customize the "control" field as in:
```

control = {}
control['max_treedepth'] = 20
control['adapt_delta'] = 0.99

fit = pystan.stan(model_code=stan_code, data=regression_data, seed=seed, iter=iterations, chains=chains, warmup=warmup, n_jobs=jobs, control=control)

```

The code does not converge. Either it overloads the memory, showing MemoryError (which I can see while it is running through the command line) or it enters a sort of infinite loop -- last night it ran all night and didn't converge. 

My question is basically: is this a known problem? If so, why does this happen? 
Also, is there a more "intelligent" way to solve this situation?
Of course, I can just ignore the warning and go on, but I'm a bit worried regarding the potential problems the output may show (which I haven't yet checked in detail).

**Comment by ahartikainen** [comment]
Hi, the memory error is probably happening on the Stan side (I could be wrong about this).

Not knowing what kind of model you have, I would assume that the posterior shape is challenging and increasing `max_treedepth` causes it's to fill your memory.


But I would suggest that you ask this in our Discourse.

Have you tried to run this model with CmdStan, it uses much less memory while computing. To analyze the results on the Python, you could use ArviZ library to read output.csv files. (Currently, we are lacking the possibility to read CmdStan csv file on PyStan).

**Comment by ahartikainen** [comment]
And here is a link to our discourse. I forgot to include it the last message

https://discourse.mc-stan.org/

**Comment by mdastro** [comment]
Thanks for the answers!

> I would assume that the posterior shape is challenging and increasing max_treedepth causes it's to fill your memory.

That's my guess as well. I actually have 25 posteriors. It's a lot! It's probably because of the combination of so many posteriors and the higher max_treedepth --  which, by the way, would you mind explaining to me exactly what this does? I'm sorry if this is a basic question, but I'm still getting acquainted with STAN.
