### ISSUE TITLE
VI diagnostics

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan2#567]
I think we should add a bit more info for `.vb`. 2.19 implements `log_p__` and `log_g__` methods that are useful to decide if the VI result should be trusted or not.

We need to change `stanfit.hpp` to include 2 extra variables that are returned. After these additions VI works, but it does not return these variables (unless one saves samples to csv).

Also I think we should return diagnostic_writer results also for the user. This would probably mean we need to edit the `pystan_writer.hpp` to have a special case for VI?

**Comment by avehtari** [comment]
diagnostic_writer part is related to stan-dev/stan#2702

**Comment by ahartikainen** [comment]
I'm not sure if we will fix this issue for PyStan 2.x.

I think we would need to rewrite a lot from the `pystan_writer.hpp`. 

Also adding a comment, that these values can be accessed from the `sample_file` (or `diagnostic_file`?) csv files that are created during the vb.

```
sample_file (string, optional) – File name specifying where samples for all parameters and other saved quantities will be written. If not provided, samples will be written to a temporary file and read back in. If the folder given is not writable, a temporary directory will be used. When there are multiple chains, an underscore and chain number are appended to the file name. By default do not write samples to file.
diagnostic_file (string, optional) – File name specifying where diagnostics for the variational fit will be written.
```
