### ISSUE TITLE
How to get the termination result?

### ISSUE THREAD

**Issue by jprawiharjo** [stan-dev/pystan2#590]
#### Summary:
How to get optimization termination status?

#### Description:

I'm using fbprophet package, which in turns uses pystan. 
I would like to get the termination status, whether it's normal or error, and the corresponding message:

`Optimization terminated with error: ...`
`Optimization terminated normally: ...`

What is the right way to get them?

#### PyStan Version:
2.19.0?

**Comment by ahartikainen** [comment]
Currently you can't access it with conventional methods. If you are on unix / osx you can use these instructions to scare that information from C++ output

https://gist.github.com/ahartikainen/06192df9719031cf1a22b887b7b5d67b

Currently, I don't know if there is any option to grab C++ on Windows, maybe some tricks with powershell, but I can't help you with that.
