### ISSUE TITLE
pip3 install git+https://github.com/stan-dev/pystan don't work

### ISSUE THREAD

**Issue by supreme-core** [stan-dev/pystan2#613]
#### Summary:
Encounter error on installation

#### Description:
Encounter error on installation

#### Reproducible Steps:
pip3 install git+https://github.com/stan-dev/pystan

#### Current Output:
```
Please see the attachment
[pip3_error.txt](https://github.com/stan-dev/pystan/files/3274019/pip3_error.txt)
```

#### PyStan Version:
Current version 

#### Python Version:
Python 3.7

#### Operating System:
Ubuntu 18

**Comment by ahartikainen** [comment]
Do you have C++ installed?

Does vanilla `pip install pystan` work? Can you compile the example 8-schools?
