### ISSUE TITLE
Version 2-19 with cvode

### ISSUE THREAD

**Issue by jg-you** [stan-dev/pystan2#614]
#### Summary:

The current release (2.19) is not shipped with a cvode version like the previous one.

#### Description:
In the [doc](https://pystan.readthedocs.io/en/latest/installation_cvodes.html), it is explained that one should install from https://github.com/stan-dev/pystan/archive/v2.18.0.0-cvodes.tar.gz to use BDF integrators.
There are no 2.19 analog, and as far as I can tell, the standard pypi install (pystan-2.19.0.0.tar.gz) doesn't support cvode.

#### Reproducible Steps:

pip install pystan and then compile any model that use integrate_ode_bdf()

#### Current Output:

    INFO:pystan:COMPILING THE C++ CODE FOR MODEL model_907c9341a1c613384e05a71328cdbef6 NOW.
    Traceback (most recent call last):
      File "compile_models.py", line 14, in <module>
        include_paths='stan_models/models_code')
      File "/usr/lib/python3.7/site-packages/pystan/model.py", line 355, in __init__
        self.module = load_module(self.module_name, lib_dir)
      File "/usr/lib/python3.7/site-packages/pystan/model.py", line 50, in load_module
        return __import__(module_name)
    ImportError: /tmp/tmpbb1lit6c/stanfit4model_907c9341a1c613384e05a71328cdbef6_6726190827278294092.cpython-37m-x86_64-linux-gnu.so: undefined symbol: CVodeGetSens

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### PyStan Version:
2.19

#### Python Version:
3.7.3

#### Operating System:

archlinux

**Comment by riddell-stan** [comment]
This is correct. Our method for getting distutils to compile models with the cvodes library stopped working, if I recall correctly.

I think it's fair to say that we're a bit backlogged with some of these build issues. Worrying about compilation of things on Windows has taken the lion's share of the time and looks likely to continue to do so.

**Comment by Dpananos** [comment]
Is it sad to say then that if we need ode capabilities, we should use rstan?

**Comment by ahartikainen** [comment]
Currently (until we fix this issue) you can use CmdStan with CmdStanPy wrapper https://github.com/stan-dev/cmdstanpy

    pip install cmdstanpy

ArviZ support CmdStanPy (and CmdStan), so plotting and diagnostics can be run with it.

https://github.com/arviz-devs/arviz
