### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError

### ISSUE THREAD

**Issue by rgerkin** [stan-dev/pystan2#620]
#### Summary:
When sampling from a large model, I get an error from the multiprocessing module after the sampling is complete and before the result is returned.  This error seems to be related to overflow during serialization for sampling results that are several GB in size.  

#### Description:
My issue is identical to [this](https://discourse.mc-stan.org/t/inference-of-huge-data-causes-an-encoding-error-by-pystan/2271) one from the mailing list. My hope in posting it here is that, in the 21 months since that was posted and answered, there is a better solution than "use CmdStan instead".  If nothing else this can be used for tracking.  @ahartikainen mentioned that there is a PR for the `multiprocessing` module that might fix this, so perhaps that can be referenced here as well.   

#### Reproducible Steps:
Sample from a sufficiently large model in PyStan.  

#### Current Output:
```
Traceback (most recent call last):
  File "/home/rgerkin/intensity.py", line 537, in sample
    sf4m = sm.sampling(data=data)
  File "/home/rgerkin/miniconda3/lib/python3.7/site-packages/pystan/model.py", line 776, in sampling
    ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
  File "/home/rgerkin/miniconda3/lib/python3.7/site-packages/pystan/model.py", line 86, in _map_parallel
    map_result = pool.map(function, args)
  File "/home/rgerkin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/rgerkin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(0, <stanfit4anon_model_375087b61fc830cf375f274c58f01b7e_3722396395666564681.PyStanHolder object at 0x7fc151742828>)]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647")'
```

#### Expected Output:
I would expect the compiled model's `sampling` method to return a result.

#### PyStan Version:
2.18.0.0

#### Python Version:
3.7.3

#### Operating System:
Ubuntu 18.04.2

**Comment by ahartikainen** [comment]
## PyStan3

PyStan3 have fixed this https://github.com/stan-dev/pystan-next

    pip install --pre pystan

## Pickle & multiprocessing

Pickle has updated itself and the default protocol is now 4, but not sure if multiprocessing is updated yet.

Python 3.8 (3.7?) could have fixed this https://github.com/python/cpython/commit/bccacd19fa7b56dcf2fbfab15992b6b94ab6666b

## CmdStanPy

On a related note, you can now use CmdStan with CmdStanPy (`pip install cmdstanpy`).

## ArviZ (current master, next release in August)

Also ArviZ has functionality to read also CmdStanPy fits and CmdStan csv, so post-processing is now easier.

https://arviz-devs.github.io/arviz/generated/arviz.from_cmdstan.html#arviz.from_cmdstan
https://arviz-devs.github.io/arviz/generated/arviz.from_pystan.html#arviz.from_pystan


    import arviz as az
    idata = az.from_pystan(fit) # works with pystan 2.x & pystan 3
    idata = az.from_cmdstan(csv_filelist)
    idata = az.from_cmdstanpy(fit)

This enables plotting and stats/diagnostics (loo etc)

    az.plot_trace(idata)
    az.plot_trace(fit)

**Comment by riddell-stan** [comment]
This is definitely fixed in PyStan 3 since we don't use pickle or multiprocessing. I'm honestly surprised you are encountering this on Python 3 since pickle should be able to handle large files.
