### ISSUE TITLE
installation of pystan and fbprophet failed

### ISSUE THREAD

**Issue by arsenvvedenskiy** [stan-dev/pystan2#633]
#### Summary:
Please provide a short couple sentence summary.
Hello! I try to install fbprophet via pip. As a result, some error occures. 

#### Description:
Describe the issue as clearly as possible.
>>> Requirement already satisfied: pystan>=2.14 in c:\users\user1\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (2.19.0.0)
nevertheless, pystan._api does not exist.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.
***
import pystan._api  # stanc wrapper
    ImportError: DLL load failed: Не найден указанный модуль.
***

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by ahartikainen** [comment]
I think we only have 64bit wheels, so you would need to compile pystan from source or use 64bit python.

**Comment by arsenvvedenskiy** [comment]
The problem is that i use 32bit python for work. Could you tell me please, how to compile pystan from source? I've never done it yet.

**Comment by ahartikainen** [comment]
Hi, try

    pip install pystan --no-binary --upgrade

**Comment by talalmts** [comment]
Hi, 
I am facing a similar error when installing pystan and fbprophet using the Dockerize version image provided by continuumio/miniconda. 
- Steps to reproduce it
> Following is the Dockerfile
```
FROM continuumio/miniconda:latest
SHELL ["/bin/bash", "-c"]
RUN conda create -n my_env python=3.6
ENV PATH /opt/conda/envs/my_env/bin:$PATH
RUN pip install pystan
RUN pip install fbprophet
```

Running the build cmd:
```docker build -t my_image . ```

Gives out the following error: 
 ```
Collecting pystan
  Downloading https://files.pythonhosted.org/packages/9f/ec/2252bcd6d93f27e726e8616b3e7ed6fb87924aede4afbed22a490980105e/pystan-2.19.0.0-cp36-cp36m-manylinux1_x86_64.whl (67.2MB)
Collecting Cython!=0.25.1,>=0.22 (from pystan)
  Downloading https://files.pythonhosted.org/packages/45/f2/a7101b3457561e57f5abcd6f5ac13190054fecd7370f58f36fe2d6574742/Cython-0.29.13-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Collecting numpy>=1.7 (from pystan)
  Downloading https://files.pythonhosted.org/packages/e5/e6/c3fdc53aed9fa19d6ff3abf97dfad768ae3afce1b7431f7500000816bda5/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
Installing collected packages: Cython, numpy, pystan
Successfully installed Cython-0.29.13 numpy-1.17.2 pystan-2.19.0.0
Removing intermediate container 4868f2b3fe29
 ---> 11fef79caada
Step 6/6 : RUN pip install fbprophet
 ---> Running in 0a961d8f09dc
Collecting fbprophet
  Downloading https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz (49kB)
Requirement already satisfied: Cython>=0.22 in /opt/conda/envs/my_env/lib/python3.6/site-packages (from fbprophet) (0.29.13)
Requirement already satisfied: pystan>=2.14 in /opt/conda/envs/my_env/lib/python3.6/site-packages (from fbprophet) (2.19.0.0)
Requirement already satisfied: numpy>=1.10.0 in /opt/conda/envs/my_env/lib/python3.6/site-packages (from fbprophet) (1.17.2)
Collecting pandas>=0.23.4 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/73/9b/52e228545d14f14bb2a1622e225f38463c8726645165e1cb7dde95bfe6d4/pandas-0.25.1-cp36-cp36m-manylinux1_x86_64.whl (10.5MB)
Collecting matplotlib>=2.0.0 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/57/4f/dd381ecf6c6ab9bcdaa8ea912e866dedc6e696756156d8ecc087e20817e2/matplotlib-3.1.1-cp36-cp36m-manylinux1_x86_64.whl (13.1MB)
Collecting lunardate>=0.1.5 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/4e/7e/377a3cbba646ec0cf79433ef858881d809a3b87eb887b0901cb83c66a758/lunardate-0.2.0-py3-none-any.whl
Collecting convertdate>=2.1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/74/83/d0fa07078f4d4ae473a89d7d521aafc66d82641ea0af0ef04a47052e8f17/convertdate-2.1.3-py2.py3-none-any.whl
Collecting holidays>=0.9.5 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/d0/17/a452275a0b3e811a381137ff6a61649086af4c5bf2a25755f518cc64b39e/holidays-0.9.11.tar.gz (81kB)Collecting setuptools-git>=1.2 (from fbprophet)
  Downloading https://files.pythonhosted.org/packages/05/97/dd99fa9c0d9627a7b3c103a00f1566d8193aca8d473884ed258cca82b06f/setuptools_git-1.2-py2.py3-none-any.whl
Collecting python-dateutil>=2.6.1 (from pandas>=0.23.4->fbprophet)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Collecting pytz>=2017.2 (from pandas>=0.23.4->fbprophet)
  Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.0.0->fbprophet)
  Downloading https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl (65kB)
Collecting cycler>=0.10 (from matplotlib>=2.0.0->fbprophet)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.0.0->fbprophet)
  Downloading https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (90kB)
Collecting ephem<3.8,>=3.7.5.3 (from convertdate>=2.1.2->fbprophet)
  Downloading https://files.pythonhosted.org/packages/b8/4c/3ec978b0882aa572741a84df73aa36467931f800b4c28090d553807c0a8f/ephem-3.7.7.0-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
Collecting six (from holidays>=0.9.5->fbprophet)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /opt/conda/envs/my_env/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->fbprophet) (41.2.0)
Building wheels for collected packages: fbprophet, holidays
  Building wheel for fbprophet (setup.py): started
  Building wheel for fbprophet (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/envs/my_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-28z58npk --python-tag cp36
       cwd: /tmp/pip-install-l1qk7u_k/fbprophet/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
  Building wheel for holidays (setup.py): started
  Building wheel for holidays (setup.py): finished with status 'done'
  Created wheel for holidays: filename=holidays-0.9.11-cp36-none-any.whl size=44784 sha256=270eca9a159f887110d5a2402b3929de5a0c6eb2c66e06109fb98ae9b1f63382
  Stored in directory: /root/.cache/pip/wheels/40/a9/2b/94ac5464363d37564a87dc93a9d21a5850aac14a4608197003
Successfully built holidays
Failed to build fbprophet
Installing collected packages: six, python-dateutil, pytz, pandas, pyparsing, cycler, kiwisolver, matplotlib, lunardate, ephem, convertdate, holidays, setuptools-git, fbprophet
  Running setup.py install for fbprophet: started
    Running setup.py install for fbprophet: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/my_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_uuqt48u/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-l1qk7u_k/fbprophet/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/envs/my_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1qk7u_k/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_uuqt48u/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
 ```


**Operating System:** 
Window 10 Enterprise

**Comment by ahartikainen** [comment]
You need update your gcc.

See https://github.com/arviz-devs/arviz/blob/master/scripts/Dockerfile

**Comment by ahartikainen** [comment]
> The problem is that i use 32bit python for work.

Hi, can you download the unofficial 32bit wheel and then (cd to correct location and) install it as 

    pip install wheelname.whl

So wheelfile for python36 32bit: [pystan-2.19.0.0-cp36-cp36m-win32.whl](https://d36102825770f036e7f0-25e1da3ee193e97cce4726db07962f5d.ssl.cf5.rackcdn.com/pystan-2.19.0.0-cp36-cp36m-win32.whl)

    pip install numpy cython
    pip install pystan-2.19.0.0-cp36-cp36m-win32.whl

**Comment by ElLorans** [comment]
I was able to install fbprophet and pystan on Windows without Anaconda following http://y-okamoto-psy1949.la.coocan.jp/Python/en1/PyStanInstalling/. I installed the components for C++ development of Desktop Applications and everything worked fine.

EDIT: to clarify, I installed Visual Studio's components for C++ development of Desktop Applications from https://visualstudio.microsoft.com/downloads/ . This solved the error

> import pystan._api # stanc wrapper
> ImportError: DLL load failed

**Comment by riddell-stan** [comment]
Thanks @ElLorans . This is really interesting.

It would be great to avoid installing mingw if we can. Or at least add that as an option. Right?

**Comment by ElLorans** [comment]
In my case, the error was caused by the lack of a C++ compiler (I was on Windows and I was not using Anaconda). I don't know the best way to permanently fix this problem without using this workaround that required a 7 GB download.

**Comment by ahartikainen** [comment]
Are you using the latest version? Can you compile models?

**Comment by ElLorans** [comment]
I am able to run the script used in the docs. 

`>>> import pystan
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)
>>> y = model.sampling().extract()['y']
>>> y.mean() `

I am using pystan 2.17.1 as suggested by http://y-okamoto-psy1949.la.coocan.jp/Python/en1/PyStanInstalling/ , as the latest version still gave me
`ImportError: DLL load failed` . Following the docs and forums, I understood that installing pystan without Anaconda was impossible, so I haven't tried to install mingw as I thought it would not work. VSC++ appears to make pystan 2.17.1 (and fbprophet) work on Windows without Anaconda, but as it required me a 7 GB download, maybe we should test if downloading mingw-w64 does the trick as well.

**Comment by ahartikainen** [comment]
Yeah, 2.17 still works with visual studio, later versions don't.

But even there (2.17 + vc++) you can not use matrix / vector code in Stan.

**Comment by ElLorans** [comment]
> Yeah, 2.17 still works with visual studio, later versions don't.
> 
> But even there (2.17 + vc++) you can not use matrix / vector code in Stan.

You are right, I had not tested it. When running the example at https://pystan.readthedocs.io/en/latest/getting_started.html I get a distutils.errors.CompileError . Should I try installing MSVC, GCC or clang-cl? Or should I give up and use Anaconda?

**Comment by ahartikainen** [comment]
There are couple of options.

1. Use miniconda and follow our official instructions.

2. Use MSVC + clang-cl
- you need to edit your distutils files or create some other clever hack to enable clang-cl.
https://github.com/ahartikainen/pystan_windows_threading

**Comment by baki077** [comment]
Hi i'm trying to deploy a python programme that uses fbprophet  with a docker image 

i usually use pip but i tried with miniconda but it still not working 

-- ----
### Dockefile
---
FROM python:3

RUN apt-get -y update && apt-get install -y
RUN apt-get -y install clang
RUN apt-get -y install gcc

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

# Install production dependencies.

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pystan
RUN pip install --no-cache-dir fbprophet
RUN echo "ALL DEPENDENCIES ARE INSTALLED ..."
CMD exec gunicorn --bind :$PORT --workers 2 --threads 8 main:app

----
`
Cython==0.29.19
Flask==1.0.2
Flask-Caching==1.9.0
flask-cors==3.0.8
Flask-Mail==0.9.1
Flask-request-params==0.3.0
google-api-core==1.17.0
google-auth==1.16.0
google-cloud-bigquery==1.24.0
google-cloud-core==1.3.0
google-cloud-datastore==1.12.0
google-cloud-storage==1.28.1
google-cloud-tasks==1.5.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
grpc-google-iam-v1==0.12.3
grpcio==1.17.1
gunicorn==20.0.4
holidays==0.10.2
idna==2.7
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==2.6.0
kiwisolver==1.2.0
korean-lunar-calendar==0.2.1
LunarCalendar==0.0.9
MarkupSafe==1.1.1
matplotlib==3.2.1
numpy==1.18.4
pandas==1.0.4
plotly==4.8.1
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyMeeus==0.3.7
pyparsing==2.4.7
pystan==2.19.1.1
python-dateutil==2.8.1
pytz==2020.1
requests==2.19.1
requests-mock==1.3.0
requests-toolbelt==0.8.0
retrying==1.3.3
rsa==4.0
setuptools-git==1.2
six==1.15.0
urllib3==1.23
Werkzeug==1.0.1
`

-------- Error ----
queue tail

  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/pystan
  creating build/temp.linux-x86_64-3.8/pystan/stan
  creating build/temp.linux-x86_64-3.8/pystan/stan/src
  creating build/temp.linux-x86_64-3.8/pystan/stan/src/stan
  creating build/temp.linux-x86_64-3.8/pystan/stan/src/stan/lang
  creating build/temp.linux-x86_64-3.8/pystan/stan/src/stan/lang/grammars
  compile options: '-DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I./pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/local/include/python3.8 -c'
  extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y'
  gcc: pystan/_api.cpp
  gcc: pystan/stan/src/stan/lang/grammars/bare_type_grammar_inst.cpp
  gcc: pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp
  In file included from pystan/stan/src/stan/lang/generator/expression_visgen.hpp:7,
                   from pystan/stan/src/stan/lang/generator/generate_expression.hpp:5,
                   from pystan/stan/src/stan/lang/generator/write_begin_all_dims_col_maj_loop.hpp:6,
                   from pystan/stan/src/stan/lang/generator.hpp:10,
                   from pystan/stan/src/stan/lang/compiler.hpp:6,
                   from pystan/stanc.hpp:2,
                   from pystan/_api.cpp:685:
  pystan/stan/src/stan/lang/generator/generate_indexed_expr.hpp: In instantiation of ‘void stan::lang::generate_indexed_expr(const string&, const std::vector<stan::lang::expression>&, stan::lang::bare_expr_type, bool, std::ostream&) [with bool isLHS = false; std::__cxx11::string = std::__cxx11::basic_string<char>; std::ostream = std::basic_ostream<char>]’:
  pystan/stan/src/stan/lang/generator/expression_visgen.hpp:117:54:   required from here
  pystan/stan/src/stan/lang/generator/generate_indexed_expr.hpp:44:35: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<stan::lang::expression>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
             && base_type.num_dims() == indexes.size()) {
                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  gcc: pystan/stan/src/stan/lang/ast_def.cpp
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  gcc: pystan/stan/src/stan/lang/grammars/expression07_grammar_inst.cpp
  gcc: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp
  In file included from pystan/stan/src/stan/lang/ast_def.cpp:97:
  pystan/stan/src/stan/lang/ast/sigs/function_signatures_def.hpp: In constructor ‘stan::lang::function_signatures::function_signatures()’:
  pystan/stan/src/stan/lang/ast/sigs/function_signatures_def.hpp:484:5: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
       function_signatures::function_signatures() {
       ^~~~~~~~~~~~~~~~~~~
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  gcc: pystan/stan/src/stan/lang/grammars/functions_grammar_inst.cpp
  gcc: pystan/stan/src/stan/lang/grammars/local_var_decls_grammar_inst.cpp
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  gcc: pystan/stan/src/stan/lang/grammars/semantic_actions_def.cpp
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  gcc: pystan/stan/src/stan/lang/grammars/statement_grammar_inst.cpp
  gcc: pystan/stan/src/stan/lang/grammars/statement_2_grammar_inst.cpp
  gcc: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  gcc: pystan/stan/src/stan/lang/grammars/whitespace_grammar_inst.cpp
  error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I./pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/local/include/python3.8 -c pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp -o build/temp.linux-x86_64-3.8/pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y" failed with exit status 1

-----------


When i add fbprophet to my requirements.txt

it says that numpy or pandas are not found despite the fact that i added them to the requirements.....

--- sometimes it builds but when running there are some errors like
pystan:No module named 'stanfit4anon_model 



Can you help me please ...

**Comment by riddell-stan** [comment]
Perhaps you are running out of RAM? See this line "gcc: fatal error: 
Killed signal terminated program cc1plus"
