### ISSUE TITLE
pars keyword in pystan.stan does nothing

### ISSUE THREAD

**Issue by bhayden53** [stan-dev/pystan2#64]
I have a model with 1000+ parameters. I am running this model on the compute nodes of of a cluster, and running into severely limiting memory issues. I can only sample ~2000 chains on each compute node before I get a memory error crash. 

Saving to a sample_file is resulting in several GB per compute node. Even using sample_file however still results in a python crash due to memory error. 

Most of the parameters of the model are hyperparameters and I am not particularly interested in their values. So I am trying to pass the pars keyword with a list of the parameters I am interested in, to reduce the memory footprint of this model. However, this seems to do nothing. If I then use fit.extract, all parameters are still being stored. In the chain file all parameters are also stored. The code for StanModel.sampling only seems to reference the pars keyword here, at line 655:

```
        if pars is not None and len(pars) > 0:
            if not all(p in m_pars for p in pars):
                pars = np.asarray(pars)
                unmatched = pars[np.invert(np.in1d(pars, m_pars))]
                msg = "No parameter(s): {}; sampling not done."
                raise ValueError(msg.format(', '.join(pars[unmatched])))
```

Am I misinterpreting the pars keyword, or is there a bug that is causing the list I pass to be ignored? I have tried intentionally adding an incorrect parameter to the list and the code does crash in the above quoted block.

**Comment by s-blume** [comment]
I seem to still be running into the same problem that @drhay53 describes. Has this issue ever been resolved?

Although I specify the parameters of interest in the pars keyword along with a sample_file in StanModel.sampling, the resulting sample file(s) still contain all parameters.
