### ISSUE TITLE
Byte string for vb filename?

### ISSUE THREAD

**Issue by mortonjt** [stan-dev/pystan2#670]
#### Summary:
Right now, `vb` returns a byte string for the file of parameters.
Specifically, if one runs a stan program like below

```python
fit = sm.vb(data=dat, iter=10000)
```

the `fit['args']['sample_file']` returns a byte string.

This is pretty awkward from a users perspective, since the user needs to manually convert it into a real string like as follows

```python
''.join(list(map(chr, fit['args']['sample_file'])))
```

I'm not familiar with the design decisions behind this - but it would be very advantageous to return a string by default rather than a byte string. 

This is run using pystan version 2.19.1.1

**Comment by ahartikainen** [comment]
Hi,

Yeah stringtype sounds more reasonable. I think that in python 3 `fit['args']['sample_file'].decode("utf-8")`

**Comment by riddell-stan** [comment]
Encoding of filenames is a surprisingly intricate topic. https://www.python.org/dev/peps/pep-0529/

Personally, I agree that str would make more sense. Changing this would be a breaking change though.

**Comment by mortonjt** [comment]
ahhh stupid windows - that makes sense now.  Closing.
