### ISSUE TITLE
Compiling on Windows without config file

### ISSUE THREAD

**Issue by yiyuezhuo** [stan-dev/pystan2#671]
I can compile on Windows following instruction. However I have installed VC compiler and still want to use it as default compiler in other non-PyStan procedure .  `distutils.cfg` seems breaking it so I delete the file and add a `setup.cfg` with same content in project directory where I may need to call PyStan.

Is it possible that I can config the value `compiler=mingw32` in Python script before calling PyStan instead of config file or modifying `distutils`?

**Comment by ahartikainen** [comment]
Can you try

    import os
    os.environ["CC"] = "gcc"
    os.environ["CXX"] = "g++" # I think this is unnecessary step

Or maybe mingw32 etc
