### ISSUE TITLE
Failed to build and install pystan on Termux

### ISSUE THREAD

**Issue by RSwarnkar** [stan-dev/pystan2#674]
#### Summary:
Please provide a short couple sentence summary.
Failed to build and install pystan on Termux Android

#### Description:
Describe the issue as clearly as possible.
Attaching log for details 

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

`pip install pystan`

If you have a reproducible example, please include it.

#### PyStan Version:
2.19.1.1
[pystan.log.txt](https://github.com/stan-dev/pystan/files/3936017/pystan.log.txt)

#### Python Version:
python 3.7.5

#### Operating System:
Android 10 MiUI

**Comment by maedoc** [comment]
looks like you ran out of memory (clang died while building).  as an aside, I once tried to do Stan on ARM (v7) it was hopelessly slow

**Comment by ahartikainen** [comment]
Yeah, I think the latest Stan needs 2gb or more to compile from sources.

You could try some older e.g. 2.12.0.0

Other thing to try is to add some extra compile args (edit setup.py)

    -flto=thin

or 

    -flto

**Comment by ahartikainen** [comment]
I'm closing this issue, because I don't think there is anything more we can do. PyStan needs a lot of RAM to compile.
