### ISSUE TITLE
Compiler errors don't surface

### ISSUE THREAD

**Issue by maedoc** [stan-dev/pystan2#675]
#### Summary:
I'm trying to reduce the C++ example for Stan [here](https://dfm.io/posts/stan-c++/) to a minimal working example, however despite the verbose output of `verbose` I can't see where the `CompilerError` is coming from.

#### Description:
I have no problem with
```stan
functions {
    real userfunc(real theta) { return -theta*theta; }
}
parameters {
    real theta;
}
model {
    target += userfunc(theta);
}
```
but if I don't define the `userfunc` function and instead provide it in C++ as 
```c++
inline double userfunc(double theta, std::ostream* pstream) {
  return -theta * theta;
}
inline var userfunc(const var & theta, std::ostream* pstream) { 
  return var(new precomp_vv_vari(userfunc(theta.val(), pstream), theta.vi_, -2*theta.val()));
}
```
(as in the linked to example), write to `userfunc.hpp` and try to compile via PyStan with
```python
model = pystan.StanModel(
    model_code=stan_code,
    allow_undefined=True,
    includes=["userfunc.hpp"],
    include_dirs=["."],
    verbose=True,
    )
```
I've got lots of C++ warnings, ~~no errors and a `CompilerError`~~ actually the error shows up somewhere in the middle of lots of warnings.

#### Current Output:
The current output is a lot of C++ warnings and the traceback of a `CompilerError` but ~~nothing useful.~~ cannot see the error.

#### Expected Output:
When I use pdb to get the relevent g++ invocation and copy paste to a new terminal, I see things like
```
./userfunc.hpp:3:153: error: no matching function for call to ‘stan::math::precomp_vv_vari::precomp_vv_vari(double, stan::math::vari* const&, double)’
    3 | ari(userfunc(theta.val(), pstream), theta.vi_, -2*theta.val())); }
      |                                                              ^
```
It would be helpful to have that report though it is perhaps mroe a bug in DistUtils?

#### PyStan Version:
v2.19.1
#### Python Version:
3.7
#### Operating System:
Ubuntu 19.04 64-bit

**Comment by maedoc** [comment]
Btw, the resolution to the bug in *my* code is to use `precomp_v_vari` since there's only one argument to the user function instead of two (`v` instead of `vv`)

**Comment by ahartikainen** [comment]
Interesting. I don't know if there is a way to increase verbosity for our builds.

Maybe distutils has some properties that are enabled currently.

**Comment by riddell-stan** [comment]
So what is producing "error: no matching function for call to ..." if not the compiler? I would think it would show up with verbose=True.

**Comment by maedoc** [comment]
> So what is producing "error: no matching function for call to ..." if not the compiler?

well of course, but if I redirect it all to a file,
```
duke@hp:~/ssd/pystanalgo$ python3 model.py &> bug.txt
[4] 22114
duke@hp:~/ssd/pystanalgo$ nl bug.txt | grep "error: no matching"
    64	./userfunc.hpp:3:153: error: no matching function for call to ‘stan::math::precomp_vv_vari::precomp_vv_vari(double, stan::math::vari* const&, double)’
duke@hp:~/ssd/pystanalgo$ nl bug.txt | tail -n1
  4505	distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
so I will edit the description to reflect this.

As mentioned, when this is run manually with g++, the error shows up at the end.  It seems like a solution would be to disable the warnings like `-Wint-in-bool-context` which might just be the compiler on Ubuntu 19.04.

**Comment by maedoc** [comment]
I will close this since in retrospect is not a PyStan issue, rather excessive GCC warnings.
