### ISSUE TITLE
Pystan to run without gcc

### ISSUE THREAD

**Issue by saravanansaminathan** [stan-dev/pystan2#679]
Summary:
               In my case I will compile the python in centos7 in a local machine then transfer it to the other machine

While installing the compiled pystan I doesn't show any error. But when I try to run the following code,

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)
y = model.sampling().extract()['y']
y.mean() # with luck the result will be near 0
```
 pystan throws the following error

    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1

PyStan Version: 2.18.1

Python Version: 3.6.3

Operating System: Centos 7

**Note**: I don't have gcc in my system. I can't able to do pip install brew or conda install brew. But I can compile the gcc in a similar environment localsetup. 

Is it possible to run pystan without gcc else what should I do?

**Comment by ahartikainen** [comment]
You can precompile the model too on another machine, pickle it and unpickle. Would that work?

How do you transfer pystan from one machine to another? Do you build the wheel and move it?

    git clone --recursive https://github.com/stan-dev/pystan
    cd pystan
    python setup.py sdist bdist_wheel
    ls dist

And copy the wheel and pip install

    pip install xxxx.whl

See our docs how to pickle model.

    https://pystan.readthedocs.io/en/latest/avoiding_recompilation.html

But to compile a new model you need gcc/clang (or some other C++ compiler).

**Comment by ahartikainen** [comment]
Can you use conda? You can install C++ compiler from conda

https://pystan.readthedocs.io/en/latest/installation_beginner.html

**Comment by saravanansaminathan** [comment]
I am compile it in a machine which has gcc 8.3.1 and transfer the site packages to another similar setup machine which has no gcc and any other c++ compiler.
Is gcc mandatory to build models or run codes in pystan?

**Comment by ahartikainen** [comment]
Yes. We translate Stan code to C++ and compile it on-the-fly.

**Comment by saravanansaminathan** [comment]
Thanks @ahartikainen for your response. Please let me know if alternatives ways are there to compile without gcc or with any other compilers

**Comment by saravanansaminathan** [comment]
Thanks @ahartikainen for your response. Please let me know if alternatives ways are there to compile without gcc or with any other compilers

**Comment by bob-carpenter** [comment]
There are no alternatives---you need a C++ compiler to compile C++.  

Packages like rstanarm precompile everything so they don't need a compiler at run time.  rstan and brms and all of our other interfaces generate C++ code and compile it for each new model.  

You can compile the code for a model on machine A and run it on binary compatible machine B (assuming the correct runtime dependencies have been installed---I think TBB works that way now).
