### ISSUE TITLE
Cannot import pystan module

### ISSUE THREAD

**Issue by ArjunSarihyan** [stan-dev/pystan2#680]
**I have trying to import the pystan module but it flashes a DLL load fail error.**

**While importing the pystan the following error flashes:**
ImportError: DLL load failed: The specified module could not be found.
---------------------------------------------------------------------------
---------------------------------------------------------------------------

**Command Used**
import pystan
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-ca8618bb8e4a> in <module>
----> 1 import pystan

c:\program files\python37\lib\site-packages\pystan\__init__.py in <module>
      7 import logging
      8 
----> 9 from pystan.api import stanc, stan
     10 from pystan.misc import read_rdump, stan_rdump, stansummary
     11 from pystan.diagnostics import check_hmc_diagnostics

c:\program files\python37\lib\site-packages\pystan\api.py in <module>
     11 import os
     12 
---> 13 import pystan._api  # stanc wrapper
     14 from pystan._compat import string_types, PY2
     15 from pystan.model import StanModel

ImportError: DLL load failed: The specified module could not be found.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
**Versions:**
os: windows10
python:  3.7.4
pystan: 2.19.1.1

**Comment by ahartikainen** [comment]
Hi did you follow our Windows instructions?

https://pystan.readthedocs.io/en/latest/windows.html

Notice, you need conda (install with e.g. anaconda/miniconda) on Windows

**Comment by Cartman0** [comment]
@ahartikainen
Hi. I want to install from pip. is this possible?

**Comment by ahartikainen** [comment]
Sure, but you still probably need m2w64.toolchain from conda to compile models.

I can see if there is a way to install those tools "manually".

**Comment by Cartman0** [comment]
@ahartikainen 
thx for reply! I could get `libmsvcr140.dll.a` and `libpython37.dll.a` in [libpython](https://anaconda.org/anaconda/libpython).
But, it is difficult to get other dependent file file(such as `vc 14` and `vs2015_runtime`) in conda...

and, i wonder that Cython code in `gensim` package works with no problem.
what's different?

**Comment by ahartikainen** [comment]
What compiler gensim uses? Our problem is msvc + c++ templates. `clang-cl` with msvc backend works (at least with 2.18?). I'm not aware if other mingw compilers work with python 3.6+.

**Comment by Cartman0** [comment]
@ahartikainen 
sorry, i may be misunderstood, because i don't install gcc, `gensim` may be worked without Cython code in my env.

**Comment by Cartman0** [comment]
@ahartikainen
I solved this `ImportError` problem for your advice with manually installing. 
But i encountered Error `Unknown MS Compiler version 1916` in `cygwinccompiler.py `.
Are there way to solve this?

process I took:
1. get `libmsvcr140.dll.a` and `libpython37.dll.a` in libpython.(i don't know this worked for detail.)
2. install msys2.
3. install mingw64-toolchain.(`pacman -S mingw-w64-x86_64-toolchain`)
3. set gcc path `C:\msys64\mingw64\bin`
4. create new file `distutils.cfg`,  write `[build]compiler=mingw32`
5. `pip install pystan`

run code (ex.eight school problem):
```
import pystan

sm = pystan.StanModel(model_code=schools_code)
sm
```
result:
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_19a09b474d1901f191444eaf8a6b8ce2 NOW.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-e1584ec6124f> in <module>
      1 import pystan
      2 
----> 3 sm = pystan.StanModel(model_code=schools_code)
      4 sm

\appdata\local\programs\python\python37\lib\site-packages\pystan\model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args, allow_undefined, include_dirs, includes)
    376 
    377         try:
--> 378             build_extension.run()
    379         finally:
    380             if redirect_stderr:

\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py in run(self)
    307                                      verbose=self.verbose,
    308                                      dry_run=self.dry_run,
--> 309                                      force=self.force)
    310         customize_compiler(self.compiler)
    311         # If we are cross-compiling, init the compiler now (if we are not

\appdata\local\programs\python\python37\lib\distutils\ccompiler.py in new_compiler(plat, compiler, verbose, dry_run, force)
   1029     # with classes that expect verbose to be the first positional
   1030     # argument.
-> 1031     return klass(None, dry_run, force)
   1032 
   1033 

\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    280     def __init__(self, verbose=0, dry_run=0, force=0):
    281 
--> 282         CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    283 
    284         # ld_version >= "2.13" support -shared so use it instead of

\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    155             # Include the appropriate MSVC runtime library if Python was built
    156             # with MSVC 7.0 or later.
--> 157             self.dll_libraries = get_msvcr()
    158 
    159     def _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts):

\appdata\local\programs\python\python37\lib\distutils\cygwinccompiler.py in get_msvcr()
     84             return ['msvcr100']
     85         else:
---> 86             raise ValueError("Unknown MS Compiler version %s " % msc_ver)
     87 
     88 

ValueError: Unknown MS Compiler version 1916 
```

**Comment by ahartikainen** [comment]
I think I can test this too. I'm not sure if vanilla mingw-w64 works with python (I think that conda toolchain has some modifications)

**Comment by Cartman0** [comment]
> I think I can test this too. I'm not sure if vanilla mingw-w64 works with python (I think that conda toolchain has some modifications)

ok,thx. where in my env , rstan is working  with no problem.you dont have to test deeply.in despite of hard times,thank you  for advising. because of be useful for all to analyse new type virus using stan, good luck for your development than this err.

**Comment by ahartikainen** [comment]
There is also `cmdstanpy` which works without conda toolchain, if you want/need to use python

**Comment by Cartman0** [comment]
> There is also `cmdstanpy` which works without conda toolchain, if you want/need to use python

thx. i try it lately.

**Comment by tangjinxing** [comment]
> > There is also `cmdstanpy` which works without conda toolchain, if you want/need to use python
> 
> thx. i try it lately.

I have the same problem, have you solved it

**Comment by Cartman0** [comment]
@tangjinxing 
hi, you should use cmdstanpy https://cmdstanpy.readthedocs.io/en/latest/getting_started.html .

and if you have a problem in install_cmdstan, view this https://github.com/stan-dev/cmdstanpy/issues/100.

**Comment by tangjinxing** [comment]
> @tangjinxing
> hi, you should use cmdstanpy https://cmdstanpy.readthedocs.io/en/latest/getting_started.html .
> 
> and if you have a problem in install_cmdstan, view this [stan-dev/cmdstanpy#100](https://github.com/stan-dev/cmdstanpy/issues/100).
sorry I don't know how to use
Can tell me the details of solving the problem of ImportError: DLL load failed

**Comment by tangjinxing** [comment]
@Cartman0 
sorry!  I don't know how to use cmdstanpy
Can tell me the details of solving the problem of ImportError: DLL load failed

**Comment by Cartman0** [comment]
@tangjinxing 
cmdstanpy is another module from pystan.https://cmdstanpy.readthedocs.io/en/latest/getting_started.html .
you need to install cmdstanpy.

**Comment by ahartikainen** [comment]
@tangjinxing are you sure you have the same problem as in this PR? You are on windows and can not use conda?

**Comment by tangjinxing** [comment]
@ahartikainen yes, I'm sure
