### ISSUE TITLE
`make` as a build requirement

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan2#681]
2.21 needs libttbb build and that code contains alot OS specific settings. I think it is much easier to build it with make (and pack it in to wheel) than manually setup it.

This also means we probably need to overwrite some distutils Classes, which is not optimal.

cc @riddell-stan

**Comment by riddell-stan** [comment]
I looked quickly at one or two of the TBB PRs and didn't spot any dramatic expansion of the build steps. Can you point me to the changes that you are thinking about?

**Comment by ahartikainen** [comment]
I'm looking to https://github.com/stan-dev/math/tree/develop/lib/tbb_2019_U8/build and https://github.com/stan-dev/math/blob/develop/lib/tbb_2019_U8/Makefile

Also, I need to follow what files are needed to `libtbb.dll` and what are for other `.dll`.

For example, calling `mingw32-make.exe compiler=gcc` in TBB main folder (on Windows 10) results in https://gist.github.com/ahartikainen/1e4b123b914db8e87eb4b9a8ec1b411b

**Comment by riddell-stan** [comment]
By "build" requirement do you mean for model compilation -- or just something to build the initial pystan wheel? If it's the second, then there's no problem at all. We already use `make` with travis, right?

**Comment by ahartikainen** [comment]
For the wheel.

Stan needs libtbb (libtbb.dll) and this can be build at the setup.

Where do we use make (I think we use it in httpstan)

**Comment by riddell-stan** [comment]
Yes, this is fine. I think we'll have to go with whatever works at this point. And I agree with the concern here: we don't want to rewrite all the make rules in distutils.

I wonder if we might be able to call out to `make` and then use numpy's `install_clib` to do the final bit of work.

The protobuf python README describes the required steps, more or less: https://github.com/protocolbuffers/protobuf/tree/master/python
