### ISSUE TITLE
[pystan/fbprophet] pystan:No module named 'stanfit4anon_model 

### ISSUE THREAD

**Issue by qrdbr** [stan-dev/pystan2#684]
#### Summary:
I am with troubles with pystan and fbprophet.

#### Description:
The following warnings is showed when I try to execute "import fbprophet" in Anaconda Prompt:

WARNING:pystan:No module named 'stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_6361530531783275681'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.

#### Reproducible Steps:
I have installed Anaconda Navigator 1.9.7.
In my job I can only use pip command (conda command is not allowed).

I execute with successful the following commands:
pip install pystan==2.18
pip install holidays==0.9.5
pip install convertdate==2.1.2
pip install lunardate==0.1.5
pip install setuptools-git==1.2

I have downloaded the following packages:

fbprophet-0.5-py36h6538335_3.tar.bz2
libpython-2.1-py37_0.tar.bz2
m2w64-toolchain-5.3.0-7.tar.bz2

Then I have installed each one:
conda install --offline fbprophet-0.5-py36h6538335_3.tar.bz2
conda install --offline libpython-2.1-py37_0.tar.bz2
 conda install --offline m2w64-toolchain-5.3.0-7.tar.bz2

#### Current Output:
(base) C:\Users\denis>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbprophet
WARNING:pystan:No module named 'stanfit4anon_model_db8febf10f23d7fa27a62fbcfd7f17b2_6361530531783275681'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.

#### Expected Output:
No warning for pystan is expected
I tried to unnistall pystan and install again. But still no working...

#### PyStan Version:
pystan 2.18

#### Python Version:
Python 3.7.3

#### Operating System:
Windows 10

**Comment by ahartikainen** [comment]
I think you need to parse and find what other files belong to that toolchain.

**Comment by baki077** [comment]
@ahartikainen  How ? i have the same problem
WARNING:pystan:No module named 'stanfit4anon_model_888a84912910fa0a45b9d614b75bb8a8_2240366454984249023'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.

**Comment by ahartikainen** [comment]
One way is to install toolchain with conda, and then try to find all the needed files and transfer them to the second computer.

In the best case it's only 1 or 2 folders + setting up the PATH
