### ISSUE TITLE
command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by titecher** [stan-dev/pystan2#688]
#### Summary:
To use pystan in not-anaconda environment, 
I face the problem that outputs the error text as described in the title.
With anaconda environment, it works well as if there were no problems.

I tried to take over this problem over a week. exausted...
Ofcourse, I read several issues and FAQ in stackoverflow, however, didnot work for me.

#### Description:
OS: Linux
GCC: 
`gcc version 7.3.1 20180712 (Red Hat 7.3.1-6) (GCC) `
Python: 3.7.4

With anaconda3, I followed the official document and pystan works without any problems.
After installing anaconda3, I introduce gcc_linux-64 to conda environment apart from original gcc.

Without anaconda3, I execute `pip3 install pystan`. This enables me import pystan in python script.
However, the third line makes error.
`import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)`

It outputs

`---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
/usr/lib64/python3.7/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    126             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
--> 127                        extra_postargs)
    128         except DistutilsExecError as msg:

/usr/lib64/python3.7/distutils/ccompiler.py in spawn(self, cmd)
    908 
--> 909     def spawn(self, cmd):
    910         spawn(cmd, dry_run=self.dry_run)

/usr/lib64/python3.7/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

/usr/lib64/python3.7/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-96-973d9bffecdb> in <module>
      1 import pystan
      2 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
----> 3 model = pystan.StanModel(model_code=model_code)

/usr/local/lib64/python3.7/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args, allow_undefined, include_dirs, includes)
    376 
    377         try:
--> 378             build_extension.run()
    379         finally:
    380             if redirect_stderr:

/usr/lib64/python3.7/distutils/command/build_ext.py in run(self)
    338 
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 
    342     def check_extensions_list(self, extensions):

/usr/lib64/python3.7/distutils/command/build_ext.py in build_extensions(self)
    447             self._build_extensions_parallel()
    448         else:
--> 449             self._build_extensions_serial()
    450 
    451     def _build_extensions_parallel(self):

/usr/lib64/python3.7/distutils/command/build_ext.py in _build_extensions_serial(self)
    472         for ext in self.extensions:
    473             with self._filter_build_errors(ext):
--> 474                 self.build_extension(ext)
    475 
    476     @contextlib.contextmanager

/usr/lib64/python3.7/distutils/command/build_ext.py in build_extension(self, ext)
    532                                          debug=self.debug,
    533                                          extra_postargs=extra_args,
--> 534                                          depends=ext.depends)
    535 
    536         # XXX outdated variable, kept here in case third-part code

/usr/lib64/python3.7/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

/usr/lib64/python3.7/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    127                        extra_postargs)
    128         except DistutilsExecError as msg:
--> 129             raise CompileError(msg)
    130 
    131     def create_static_lib(self, objects, output_libname,

CompileError: command 'gcc' failed with exit status 1`

I add /path to gcc/ to PATH 

If possible, 
let me know how to set up pystan without anaconda.
Pystan is so attractive. I cannnot give up it.

**Comment by riddell-stan** [comment]
A couple of questions for you:
1. You are running on RHEL7 with gcc 4.8.x being the default compiler, right?
2. Have you set the CC environment variable to be the path to the newer gcc?

What is the path to the newer gcc? I believe you need to type this before using pystan:

```
export CC=/usr/local/bin/path/to/new/gcc
```

You'll need to do this when you install PyStan and then every time you use PyStan.

Sorry about this. RHEL7 uses an extremely old compiler. Newer Linux operating systems will not have this problem.

**Comment by titecher** [comment]
I am running on AWS linux 2. It seems based on RedHat.
However, gcc is original implemented but version is  7.3.1. 

Path is set as CC.
/usr/bin/gcc

**Comment by ahartikainen** [comment]
Do you have g++ installed?
