### ISSUE TITLE
Compiler gets stuck using spyder

### ISSUE THREAD

**Issue by Femkemilene** [stan-dev/pystan2#690]
#### Summary:
The compilation gets stuck with any stan model using Spyder. No issues from anaconda prompt.

#### Description:
Whenever I try to compile a model in spyder, it gets stuck. The example model takes about 1 minute to compile using the anaconda prompt, but still hasn't compiled after waiting a full hour when executing as a script in spyder.

#### Reproducible Steps:
I've downloaded pystan per the instruction here: https://pystan.readthedocs.io/en/latest/windows.html.

I'm running the test model:

import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code, verbose=True)
y = model.sampling().extract()['y']
y.mean()  # with luck the result will be near 0If you have a reproducible example, please include it.

#### Current Output:
Using the verbose keyword, the output is: 

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
INFO:pystan:OS: win32, Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)], Cython 0.29.15
Compiling C:\Users\Femke\AppData\Local\Temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.pyx because it changed.
[1/1] Cythonizing C:\Users\Femke\AppData\Local\Temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.pyx
building 'stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730' extension
C:\Users\Femke\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -IC:\Users\Femke\AppData\Local\Temp\pystan_zr0o36jm -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan\stan\src -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math\lib\eigen_3.3.3 -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math\lib\boost_1.69.0 -IC:\Users\Femke\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math\lib\sundials_4.1.0\include -IC:\Users\Femke\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Femke\Anaconda3\include -IC:\Users\Femke\Anaconda3\include -c C:\Users\Femke\AppData\Local\Temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.cpp -o c:\users\femke\appdata\local\temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y -D_hypot=hypot -pthread -fexceptions
writing c:\users\femke\appdata\local\temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.cp37-win_amd64.def
C:\Users\Femke\Anaconda3\Library\mingw-w64\bin\g++.exe -shared -s c:\users\femke\appdata\local\temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.o c:\users\femke\appdata\local\temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.cp37-win_amd64.def -LC:\Users\Femke\Anaconda3\libs -LC:\Users\Femke\Anaconda3\PCbuild\amd64 -lpython37 -lmsvcr140 -o C:\Users\Femke\AppData\Local\Temp\pystan_zr0o36jm\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_2350378146107186730.cp37-win_amd64.pyd

#### Expected Output:
I expect the output to be a number around zero.

#### PyStan Version:
2.19.1.1 (also tried 2.18.1.0).

#### Python Version:
3.7.4

#### Operating System:
Windows 10

**Comment by ahartikainen** [comment]
Hi, thanks for the issue.

I don't personally use spyder, but I know there have been some problems previously.

Apparently it does compile the model (.pyd file).

Do you know if it fails at `.sampling` step or at import step? Can you add some prints?

Does it work with `n_jobs=1` (for sampling)

**Comment by Femkemilene** [comment]
You're right, it's not the compiling that's the issue. When I comment out the last two lines, the code doesn't get stuck.

It works if I set n_jobs=1! So the problem is the sampling. 

Adding verbose=True for the sampling statement doesn't lead to more information. What prints would be helpful?

**Comment by ahartikainen** [comment]
I think this is probably a problem with multiprocessing and spyder.

See

https://discourse.mc-stan.org/t/compiler-getting-stuck-when-chain-number-is-larger-than-1/13264/10

and link in there

https://stackoverflow.com/questions/34821877/joblib-parallel-running-through-spyder-hanging-on-windows

Not sure if there is any solution
