### ISSUE TITLE
Expose laplace approximation

### ISSUE THREAD

**Issue by groceryheist** [stan-dev/pystan2#694]
#### Summary:

The [mc-stan 2.22 reference](https://mc-stan.org/docs/2_22/reference-manual/analysis-chapter.html) indicates that the optimization algorithm provides laplace approximations for posterior analysis. Pystan should support drawing random values from this approximate distribution.

**Comment by ahartikainen** [comment]
Hi, thanks for the suggestion. I will need to check when this landed and how to call it. 2.22 update (PR still open) might already support this.

**Comment by groceryheist** [comment]
Thanks, from scanning the PR it doesn't seem like it is supported, but I don't know anything about how pystan works. I tried installing the PR but had trouble getting the right commit of stan and stan_math in the submodules.  I care a lot about this as I'm working on some models where mc is pretty slow and it would be great to iterate using Laplace approximations.

**Comment by avehtari** [comment]
@bbbales2 is working on implementing this in Stan/CmdStan

**Comment by bbbales2** [comment]
Yeah that's a problem with the documentation :P. It's something we want. I'd say it's a coinflip for 2.24 in 3 months.

**Comment by dionman** [comment]
Is Laplace approximation supported at the latest version of pystan already?

**Comment by bbbales2** [comment]
@dionman I think not. I didn't work much on the cmdstan Laplace approximation stuff for this release. I haven't heard of anything changing in Pystan either.
