### ISSUE TITLE
Documentation: HMC: Euclidian Metric

### ISSUE THREAD

**Issue by ZitongZhou** [stan-dev/pystan2#701]
#### Summary:
Sorry for indicating the documentation error in the issue section if it is not the right manner.
The code in the documentation for HMC: Euclidian Metric in this [link](https://pystan.readthedocs.io/en/latest/hmc_euclidian_metric.html) throws error when analyzing the chains.

#### Description:

1. In the second code block: case 1 numpy.concatenate, there is `extract2 = fit2.extract()`, but there is no fit2 result from the above code. Maybe adding 
`fit1 = sm.sampling(data=data,
                   warmup=0,
                   iter=1000,
                   control=control,
                   init=init,
                   seed=seed1)`?

2. Also in the second code block, `# transform shape order from (draw, chain, *shape) to (chain, draw, *shape)`, but the dimension of `arr1` and `arr2` are both (4000, ), so using `np.concatenate((arr1, arr2), axis=0)` and then swaping the axes won't transform the 'combined' array to the correct form. If using `combined[key] = np.vstack((arr1, arr2))` without swaping the order, it seems doing the right thing.

#### Reproducible Steps:
run the 1st and 2nd code blocks in this [link](https://pystan.readthedocs.io/en/latest/hmc_euclidian_metric.html)

#### Current Output:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-61-b4c0d921a9cf> in <module>()
----> 1 extract1 = fit1.extract()
      2 extract2 = fit2.extract()
      3 
      4 combined = {}
      5 for key in extract1.keys():`

AttributeError: 'NoneType' object has no attribute 'extract'

#### Expected Output:
`        mean     sd  hpd_3%  hpd_97%  ...  ess_sd  ess_bulk  ess_tail  r_hat
theta  0.591  0.140   0.328    0.844  ...  7832.0    7843.0    7162.0    1.0
lp__  -7.948  0.716  -9.256   -7.442  ...  7506.0    7650.0    7536.0    1.0

[2 rows x 11 columns]
array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f22f57e8a58>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7f22f5786f60>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x7f22f56fcfd0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7f22f5734978>]],
      dtype=object)
`

#### PyStan Version:
'2.19.1.1'
#### Python Version:
3.x
#### Operating System:
Mac + Google Colab

**Comment by ahartikainen** [comment]
Hi, 

No need to be sorry, I'm always happy when people read and try documentation.

1. You are right, it is missing `fit1`. It should be

    extract1 = fit.extract()

2. Oh, yes. You are probably right here. There is a mistake.

By default, calling `.extract` with `permuted=True` returns a dict of parameters with flattened chains.

Then there is a way to call `.extract` with `permuted=False` which returns a ndarray where each parameter is flattened to a "table"/one dim. This has shape of `draw`, `chain` and `flatparams`.
Then there is a special "hidden" way to call `.extract` with `permuted=False` and using all param names as a list for `pars` argument, which returns a dictionary where the shape has not been flattened.

So the example should really have

    extract1 = fit.extract(pars=fit.sim['pars_oi'])
    extract2 = fit2.extract(pars=fit.sim['pars_oi'])

https://pystan.readthedocs.io/en/latest/api.html

> If permuted is False and pars is not None, return dictionary with samples for each parameter (or other quantity) named in pars. The first dimension of the sample array is for the iterations; the second for the number of chains; the rest for the parameters. Parameters are listed in the same order as pars.

**Comment by ZitongZhou** [comment]
Got you! thank you for the quick reply!
________________________________
