### ISSUE TITLE
Cannot install pystan with pip on Ubuntu 20.04

### ISSUE THREAD

**Issue by domeckert** [stan-dev/pystan2#702]
Hello,

I have recently upgraded to Ubuntu 20.04, which comes with Python 3.8 as default, and I cannot install pystan (v2.19.1.1) any more with pip (used to work with Ubuntu 19.10 and Python 3.7). I get the following errors:

`x86_64-linux-gnu-gcc: pystan/stan/src/stan/lang/grammars/statement_2_grammar_inst.cpp
x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.`

`In file included from pystan/stan/src/stan/lang/ast_def.cpp:97:
pystan/stan/src/stan/lang/ast/sigs/function_signatures_def.hpp: In constructor ‘stan::lang::function_signatures::function_signatures()’:
pystan/stan/src/stan/lang/ast/sigs/function_signatures_def.hpp:474:1: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
  474 | function_signatures::function_signatures() {
      | ^~~~~~~~~~~~~~~~~~~ `

`error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I./pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.72.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -Ipystan/stan/lib/stan_math/lib/tbb/include -I/usr/include/python3.8 -c pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp -o build/temp.linux-x86_64-3.8/pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y" failed with exit status 1
`

Can anyone give me a hand?

**Comment by riddell-stan** [comment]
How much RAM do you have?

**Comment by domeckert** [comment]
I have 16 Gb of RAM. Hopefully that should be sufficient? Although it is true that the compilation appeared to use all my resources and my computer basically got stalled, I couldn't even move the mouse for a few minutes

**Comment by riddell-stan** [comment]
16G should be plenty. (Frequently RAM is a problem with crashes like this.)

Could there be some issue with an old installation of PyStan overlapping 
with the new one?

**Comment by domeckert** [comment]
I don't think so, there is an installed python3.7 version but nothing else in python3.8
