### ISSUE TITLE
reduce_sum error: "Variable "partial_sum" does not exist." : pystan 2.23?

### ISSUE THREAD

**Issue by JohannesBuchner** [stan-dev/pystan2#705]
#### Summary:

The [reduce_sum tutorial code](https://mc-stan.org/users/documentation/case-studies/reduce_sum_tutorial.html) gives "Variable "partial_sum" does not exist." in current pystan.

I suspect that this is because the pystan pypi version is at 2.19, while reduce_sum was introduced in Stan 2.23. Could you please make a release including this feature?

#### Reproducible Steps:
```pystan.StanModel("""
functions {
  real partial_sum(int[] slice_n_redcards,
                   int start, int end,
                   int[] n_games,
                   vector rating,
                   vector beta) {
    return binomial_logit_lpmf(slice_n_redcards |
                               n_games[start:end],
                               beta[1] + beta[2] * rating[start:end]);
  }
}
data {
  int<lower=0> N;
  int<lower=0> n_redcards[N];
  int<lower=0> n_games[N];
  vector[N] rating;
  int<lower=1> grainsize;
}
parameters {
  vector[2] beta;
}
model {

  beta[1] ~ normal(0, 10);
  beta[2] ~ normal(0, 1);

  target += reduce_sum(partial_sum, n_redcards, grainsize,
                       n_games, rating, beta);
}""")
```

If you have a reproducible example, please include it.

#### Current Output:

```
ValueError: Failed to parse Stan model 'anon_model_5a1f6c2405b41376d4f7ad9ac8c2ff61'. Error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Variable "partial_sum" does not exist.
 error in 'unknown file name' at line 25, column 32
  -------------------------------------------------
    23: beta[1] ~ normal(0, 10);
    24: beta[2] ~ normal(0, 1);
    25: target += reduce_sum(partial_sum, n_redcards, grainsize,
                                       ^
    26: n_games, rating, beta);
  -------------------------------------------------
```

#### Expected Output:
Successful compilation.

#### PyStan Version:
2.19.0.0

#### Python Version:
3.6.9

#### Operating System:
GNU/Linux

**Comment by ahartikainen** [comment]
Hi, yes work is underway. We probably do release for 2.22 first.

PyStan3 is going for 2.23 first, after that we need to figure out PyStan.

**Comment by JohannesBuchner** [comment]
What is PyStan3? a branch?

**Comment by ahartikainen** [comment]
https://github.com/stan-dev/pystan-next

There is also CmdStanPy which can use partial_sum already.
