### ISSUE TITLE
ERROR: Failed building wheel for pystan

### ISSUE THREAD

**Issue by samar-080301** [stan-dev/pystan2#706]
#### Summary:
I was trying to install pystan with pip install pystan, and the following problem occurred

#### Description:
 Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\users\samar\appdata\local\programs\python\python38\lib\site-packages (from pystan) (0.29.17)

Requirement already satisfied: numpy>=1.7 in c:\users\samar\appdata\local\programs\python\python38\lib\site-packages (from pystan) (1.18.3)

 No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I.\pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -Ic:\users\samar\appdata\local\programs\python\python38\include -Ic:\users\samar\appdata\local\programs\python\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tppystan/_api.cpp /Fobuild\temp.win-amd64-3.8\Release\pystan/_api.obj /EHsc -DBOOST_DATE_TIME_NO_LIB /std:c++14
  _api.cpp
  c:\users\samar\appdata\local\programs\python\python38\include\features.h(360): fatal error C1083: Cannot open include file: 'gnu/stubs.h': No such file or directory
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I.\pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -Ic:\users\samar\appdata\local\programs\python\python38\include -Ic:\users\samar\appdata\local\programs\python\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tppystan/_api.cpp /Fobuild\temp.win-amd64-3.8\Release\pystan/_api.obj /EHsc -DBOOST_DATE_TIME_NO_LIB /std:c++14" failed with exit status 2

#### Current Output:
ERROR: Failed building wheel for pystan

#### Expected Output:
pystan successfully installed

#### PyStan Version:
pystan-2.19.1.1
#### Python Version:
3.8.1
#### Operating System:
Windows 10 home 64bit

**Comment by ahartikainen** [comment]
Hi,

follow our instructions in the docs

https://pystan.readthedocs.io/en/latest/windows.html

You need to use mingw-w64-toolchain from conda.
