### ISSUE TITLE
Is `fit.extract` return right order samples?

### ISSUE THREAD

**Issue by xujiaze13** [stan-dev/pystan2#707]
#### Description:
The output of `fit.extract` returns posterior samples.
But its order is different from `az.plot_trace`
So how could I extract posterior samples with right orders.

Here is my code

> 
> import pystan
> import matplotlib.pyplot as plt
> import arviz as az
> 
> schools_code = """
> data {
>     int<lower=0> J; // number of schools
>     real y[J]; // estimated treatment effects
>     real<lower=0> sigma[J]; // s.e. of effect estimates
> }
> parameters {
>     real mu;
>     real<lower=0> tau;
>     real eta[J];
> }
> transformed parameters {
>     real theta[J];
>     for (j in 1:J)
>         theta[j] = mu + tau * eta[j];
> }
> model {
>     eta ~ normal(0, 1);
>     y ~ normal(theta, sigma);
> }
> """
> 
> schools_dat = {'J': 8,
>                'y': [28,  8, -3,  7, -1,  1, 18, 12],
>                'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
> 
> sm = pystan.StanModel(model_code=schools_code)
> fit = sm.sampling(data=schools_dat, iter=100, chains=1, seed=1)
> 
> az.plot_trace(fit, var_names=['mu'])
[trace.pdf](https://github.com/stan-dev/pystan/files/4775760/trace.pdf)
> fig, ax = plt.subplots()
> ax.plot(fit['mu'])
[extract.pdf](https://github.com/stan-dev/pystan/files/4775761/extract.pdf)

**Comment by ahartikainen** [comment]
Hi

There are couple ways

    fit_ext = fit.extract(permuted=False) # ndarray, not same as permuted=True
    idata = az.from_pystan(fit) # InferenceData object
    df = fit.to_dataframe() # pandas.DataFrame

Or manually resort values (sorting order is somewhere in the fit object and after that it is some manual resorting)
