### ISSUE TITLE
Should create Official Docker image for pystan!

### ISSUE THREAD

**Issue by Cartman0** [stan-dev/pystan2#709]
#### Summary:
(this is proposal)

Are there Official Docker image for pystan now ?
https://hub.docker.com/search?q=pystan&type=image

#### Description:
available WSL2 from Windows10 ver2004, then available Docker.
for this, can manage different dev environment by docker image .
for example, 
- separate complex toolchain from system tool.
- creating stan-dev-env simply and easily using `docker pull` command from docker hub

How about creating Official Docker image ?

**Comment by ahartikainen** [comment]
Hi, we don't have any official docker.

One could create some base docker, but what tools would be suitable for the it.

**Comment by Cartman0** [comment]
hi.

how unix env stan-developers work and test on?
indivisually i want docker image working on ubuntu20.04LTS.

**Comment by ahartikainen** [comment]
Not sure, I split my dev time between Windows (80%) and Linux (20%), but still mostly use same tools (conda).

But docker stuff usually needs a minimal set of tools. Then it is only a way we want to user to use the base docker.

E.g. do we want to have base docker with working pystan and user can install other tools in their own docker file. Or do we want to have a working modelling env with jupyter and other tools.

**Comment by Cartman0** [comment]
i dont know about docker for detail.
if my understand is correct, 
users can use other tools too because users can add it into docker image by using docker commit command.

https://docs.docker.com/engine/reference/commandline/commit/

so, i think there is docker image working pystan only

**Comment by ahartikainen** [comment]
Here is one example for a docker, which is for dev work

https://github.com/arviz-devs/arviz/blob/master/scripts/Dockerfile

As you see, it inherits conda docker. In similar fashion we could create an dockerfile which has 'minimal' tools to get pystan working and then users could use that to inherit or just use as is.

Now, the question is, what is 'minimal' toolset. (E.g. should we include viz tools too)

**Comment by Cartman0** [comment]
ok, i see...
It may be kind to prepare both minimum and all-in-pack-frequently-used-tools.
but, the later may become that the test and support is hard.

i dont know tools required in stan for detail,
need discuss with other stan-developers..

- thinking stan-beginner or user-friendly, all-in-pack maybe useful..
- thinking developers familiar with dev-env, minimum maybe useful.. (ex. using windows terminal, because of running each container in each tab(pane), stan-only container and other container for other analizing and visualizing maybe useful ..  )

**Comment by Cartman0** [comment]
hi, i up info we may have to refer .

jupyter's Docker Image is follow.

![inherit](https://user-images.githubusercontent.com/10578703/88040753-51fedc00-cb84-11ea-817f-202b71681a41.PNG)

> ref: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

where using jupyter and pystan, 
pystan image may have to inherit [`minimal-notebook`](https://hub.docker.com/r/jupyter/minimal-notebook/) or [`scipy-notebook`](https://hub.docker.com/r/jupyter/scipy-notebook).

By the way, all jupyter's image depends `conda`,
and `scipy-notebook` include `cython`.

(i don't try to make prototype-dockerfile yet)

**Comment by ahartikainen** [comment]
Hi 

Fyi

https://discourse.mc-stan.org/t/docker-stan/14966

and

https://github.com/stan-dev/stan/wiki/Stan-Docker-Image-Plans

**Comment by Cartman0** [comment]
@ahartikainen thx for creating wiki page!

**Comment by Cartman0** [comment]
ok, have to follow and prior the discourse flow.
which stan tool(cmdstan, rstan, pystan, cmdstanpy and etc...) focus on in the discourse?

**Comment by Cartman0** [comment]
> ## Important Questions
- Which interfaces and components in StanDev should get their own dedicated image?

interfaces and components by installing with `pip` or `conda` / is useless?

**Comment by Cartman0** [comment]
i created minimum simple/naive pystan image.

Dockerfile:

```
# gcc
FROM gcc:latest as env-gcc

FROM python:3
# add path
ENV LD_LIBRARY_PATH "/usr/local/lib:${LD_LIBRARY_PATH}"
# requirement1 gcc
COPY --from=env-gcc . .
# requirement2
RUN pip install Cython
# requirement3
RUN pip install numpy
# install pystan
RUN pip install pystan
```

build on powershell(windows terminal):
```
cd <dockerfile>
docker build -t pystan .
```

run container:
```
docker run -it --name pystan-test pystan python
```

python shell on container:

```python
import pystan
school_code = """\
data {\
     int<lower=0> J; \
     vector[J] y; \
     vector<lower=0>[J] sigma; \
}\
parameters {\
     real mu;\
     real<lower=0> tau;\
     vector[J] eta;\
}\
transformed parameters {\
    vector[J] theta;\
    theta = mu + tau * eta;\
}\
model {\
    eta ~ normal(0, 1);\
    y ~ normal(theta, sigma);\
}\
"""
schools_dat = {'J': 8,\
               'y': [28,  8, -3,  7, -1,  1, 18, 12],\
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
sm = pystan.StanModel(model_code=schools_code)
```
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_9160ce661d750f6ad8c0452552f003d6 NOW.
```

```python
fit = sm.sampling(data=schools_dat, iter=1000, chains=4)
```
```
Gradient evaluation took 1.2e-05 seconds
Gradient evaluation took 1.4e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.12 seconds.
1000 transitions using 10 leapfrog steps per transition would take 0.14 seconds.
Adjust your expectations accordingly!
Adjust your expectations accordingly!




Iteration:   1 / 1000 [  0%]  (Warmup)
Iteration:   1 / 1000 [  0%]  (Warmup)

Gradient evaluation took 1.3e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.13 seconds.
Adjust your expectations accordingly!



Iteration:   1 / 1000 [  0%]  (Warmup)
Gradient evaluation took 1.3e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.13 seconds.
Adjust your expectations accordingly!


Iteration:   1 / 1000 [  0%]  (Warmup)
Iteration: 100 / 1000 [ 10%]  (Warmup)
Iteration: 100 / 1000 [ 10%]  (Warmup)
Iteration: 100 / 1000 [ 10%]  (Warmup)
Iteration: 100 / 1000 [ 10%]  (Warmup)
Iteration: 200 / 1000 [ 20%]  (Warmup)
Iteration: 200 / 1000 [ 20%]  (Warmup)
Iteration: 200 / 1000 [ 20%]  (Warmup)
Iteration: 200 / 1000 [ 20%]  (Warmup)
Iteration: 300 / 1000 [ 30%]  (Warmup)
Iteration: 300 / 1000 [ 30%]  (Warmup)
Iteration: 300 / 1000 [ 30%]  (Warmup)
Iteration: 300 / 1000 [ 30%]  (Warmup)
Iteration: 400 / 1000 [ 40%]  (Warmup)
Iteration: 400 / 1000 [ 40%]  (Warmup)
Iteration: 400 / 1000 [ 40%]  (Warmup)
Iteration: 400 / 1000 [ 40%]  (Warmup)
Iteration: 500 / 1000 [ 50%]  (Warmup)
Iteration: 501 / 1000 [ 50%]  (Sampling)
Iteration: 500 / 1000 [ 50%]  (Warmup)
Iteration: 501 / 1000 [ 50%]  (Sampling)
Iteration: 500 / 1000 [ 50%]  (Warmup)
Iteration: 501 / 1000 [ 50%]  (Sampling)
Iteration: 500 / 1000 [ 50%]  (Warmup)
Iteration: 501 / 1000 [ 50%]  (Sampling)
Iteration: 600 / 1000 [ 60%]  (Sampling)
Iteration: 600 / 1000 [ 60%]  (Sampling)
Iteration: 600 / 1000 [ 60%]  (Sampling)
Iteration: 600 / 1000 [ 60%]  (Sampling)
Iteration: 700 / 1000 [ 70%]  (Sampling)
Iteration: 700 / 1000 [ 70%]  (Sampling)
Iteration: 800 / 1000 [ 80%]  (Sampling)
Iteration: 700 / 1000 [ 70%]  (Sampling)
Iteration: 800 / 1000 [ 80%]  (Sampling)
Iteration: 700 / 1000 [ 70%]  (Sampling)
Iteration: 900 / 1000 [ 90%]  (Sampling)
Iteration: 900 / 1000 [ 90%]  (Sampling)
Iteration: 800 / 1000 [ 80%]  (Sampling)
Iteration: 800 / 1000 [ 80%]  (Sampling)
Iteration: 1000 / 1000 [100%]  (Sampling)
Iteration: 1000 / 1000 [100%]  (Sampling)


 Elapsed Time: 0.017362 seconds (Warm-up)
               0.014944 seconds (Sampling)
 Elapsed Time: 0.016661 seconds (Warm-up)
               0.01544 seconds (Sampling)
               0.032306 seconds (Total)

               0.032101 seconds (Total)

Iteration: 900 / 1000 [ 90%]  (Sampling)
Iteration: 900 / 1000 [ 90%]  (Sampling)
Iteration: 1000 / 1000 [100%]  (Sampling)

 Elapsed Time: 0.01828 seconds (Warm-up)
               0.022022 seconds (Sampling)
               0.040302 seconds (Total)

Iteration: 1000 / 1000 [100%]  (Sampling)

 Elapsed Time: 0.017918 seconds (Warm-up)
               0.023141 seconds (Sampling)
               0.041059 seconds (Total)
```

**Comment by Cartman0** [comment]
because include `gcc-tool-chain` in python image, can actually remove gcc image..

Dockerfile
```
FROM python:3
# add libpython path
ENV LD_LIBRARY_PATH "/usr/local/lib:${LD_LIBRARY_PATH}"
# requirement2
RUN pip install Cython
# requirement3
RUN pip install numpy
# install pystan
RUN pip install pystan
```

**Comment by ahartikainen** [comment]
I think that sounds great.

So if we wanted then add some extra libs (jupyterlab, pandas, mpl, arviz, bokeh; ffmpeg etc for animation maybe) and config jupyterlab, we could just inherit that simple image.

**Comment by Cartman0** [comment]
for jupyter, may have to inherit any one of `jupyter`  image.

benefits:
- disk space need to create image / become less  by docker image layer, if already use jupyter image (jupyter size is GB-scale)

for exmaple, Dockerfile:
```
FROM jupyter/scipy-notebook
RUN conda install pystan
```

**Comment by ahartikainen** [comment]
I think we can still install with pip.

**Comment by Cartman0** [comment]
yes, can use pip, but the docker image(pystan-jupyter) size is larger, so that it is not good.

the file by `pip install jupyter` / will be different from `jupyter/xxx-notebook` image layer on Docker.

thinking to install follow docker images:

- Image:jupyter/xxx-notebook, **layerID: aaa**

- Image:stan/jupyter-pystan, layerID: bbb
  - `FROM jupyter/xxx-notebook`, **layerID: aaa (same as above)**
  - `RUN conda install pystan`, layerID: bbb

- Image:stan/pystan-jupyter, layerID: eee(size will be larger than layer bbb)
  - `FROM stan/pystan`, layerID: ddd
  - `RUN pip install jupyter`, layerID: eee

**Comment by ahartikainen** [comment]
Would it help to combine pip commands?

Also is there something we can remove to make the image smaller (cache etc?)

**Comment by Cartman0** [comment]
ok, my description was not exact, follow situation was more exact:

- Image:jupyter/xxx-notebook, layerID: **aaa**

- Image:stan/pystan, layerID: *bbb*

- Image:stan/jupyter-pystan, layerID: ccc
  1. `FROM jupyter/xxx-notebook`, layerID: **aaa (same as above)**
  2. `RUN conda install pystan`, layerID: ccc(over aaa)

- Image:stan/pystan-jupyter, layerID: eee
  1. `FROM stan/pystan`, layerID: *bbb(same as above)*
  2. `RUN pip install jupyter`, layerID: ddd(over bbb)
  3. set config of jupyter, layerID:  eee(over ddd)

\* where layer ID is same, the file actually is one on host PC.

i don't know exactly which image size( layerID ccc or eee) will be larger.
image layer relationship may be clear to inherit jupyter-image.

however, where jupyter image, changed to add USER and working directory `/home/jovyan/work` for mounting working directory on hostPC, different from the way to use `pip install jupyter && jupyter notebook`. if add jupyter, i think should inherit the way to use in jupyter image.

**Comment by Cartman0** [comment]
MEMO:
for running pystan at high-speed, 
need to check if can enable `--gpu` option when `docker run`. 

- https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu
- https://github.com/NVIDIA/nvidia-docker/tree/master#quickstart (not support windows?, supported in "CUDA on WSL2"?) 
- https://qiita.com/ksasaki/items/b20a785e1a0f610efa08 (japanese)
- https://qiita.com/ksasaki/items/ee864abd74f95fea1efa (japanese)

**Comment by ahartikainen** [comment]
Does this affect cpu use?

**Comment by Cartman0** [comment]
@ahartikainen 
it can commonly run on cpu without gpu option.(i dont try yet)
Docker supports currently only NVIDIA GPU.
seemed to change to control cpu/gpu by using `--gpus`option in docker side from docker 19.03.


however, the docker-image seems to need to be using CUDA  for getting benefits of gpu.   
by the way, NGC(nvidia official) container supports gpu/CUDA (https://ngc.nvidia.com/catalog/all?orderBy=modifiedDESC&pageNumber=1&query=&quickFilter=all&filters=).

pystan is written by CUDA/nvcc?

**Comment by ahartikainen** [comment]
We don't currently support GPU with PyStan. This might change in future (Stan has some support for GPU), but even then Stan uses opencl.

**Comment by Cartman0** [comment]
@ahartikainen 
because seems that NVIDIA especially pays attention to CUDA in only Docker, 
may become difficult to run opencl on Docker.

updating of `nvidia/opencl` image is stopping before a year... 
https://hub.docker.com/r/nvidia/opencl

**Comment by elbamos** [comment]
Has anyone at this point come up with a working, minimal, pystan docker?  I am attempting to do so in https://github.com/stan-dev/pystan/issues/742 and would appreciate any advice or a recipe?
