### ISSUE TITLE
Extract posterior samples from Variational Bayes fit object

### ISSUE THREAD

**Issue by dionman** [stan-dev/pystan2#710]
Are there any updates on adding a feature similar to ```sampling().extract()``` for ```vb``` fits on a statistical model? Currently producing samples from variational posteriors seems quite tedious/slow

**Comment by ahartikainen** [comment]
Hi, I think you could use ArviZ (`az.from_dict`) to get better interface for the random samples in the results.

    import arviz as az
    ...
    res = stan_model.vb()
    idata = az.from_dict(dict(zip(res["sampler_param_names"], res["sampler_params"])))
    # then see idata.posterior

or to keep your mean values with you, you can do a little hack

    idata = az.from_dict(
        posterior=dict(zip(res["sampler_param_names"], res["sampler_params"])),
        sample_stats=dict(zip([item+"_mean" for item in res["mean_par_names"]], res["mean_pars"]))
    )

But you would still need to manually combine the results (vector / matrices) before using `az.from_dict`.

**Comment by soerenberg** [comment]
> Are there any updates on adding a feature similar to `sampling().extract()` for `vb` fits on a statistical model? Currently producing samples from variational posteriors seems quite tedious/slow

I wrote a small function to combine the samples coming from vb https://github.com/soerenberg/stan-vb-extract . Maybe that's what you are looking for (at least partially)?
Feel free to use it as you like.
