### ISSUE TITLE
Reproducibility on different machines

### ISSUE THREAD

**Issue by MaxRCohen** [stan-dev/pystan2#711]
#### Summary:
Using the seed and init functionality, I get reproducible results on one computer. However, I get a different set of results on another computer for the same exact inputs. The results are reproducible within multiple runs on the same computer, but they differ on different computers.

#### Description:
For the "optimizing" and "sampling" functions of PyStan, I cannot create reproducible results on different computers. I am sure to set both the init and the seed variables as inputs. On one computer with multiple runs, I always get the same outputs. On the other computer I am using, I also get the same outputs for every run, but it is a different set of outputs than I get from the 1st computer. The computers are consistent with themselves, but not consistent with each other.

A strange thing is that for the "vb" functions of PyStan, I get the same outputs across all computers.

Note: for all 3 functions, I'm using the same cached model. 

Can you help me understand why this is happening? I'd like to be able to reproduce my outputs across all computers I work on.

**Comment by MaxRCohen** [comment]
Hi,

I realize including a simple example of my PyStan code might help resolve this issue faster. In this Zip file, I've included the python script I'm using to generate MCMC samples from the data (provided in the Excel sheet named "Data"). The Excel sheet named "Compare_catalog" details the differences I'm seeing on different machines for this exact same script and input.

Note in the script, I specify the seed and init variables. Again, I get reproducibility within a given machine (always getting the same samples from repeat runs on a given machine), but the results do not match across machines.

Thank you for your help with this issue.

[reproducibility.zip](https://github.com/stan-dev/pystan/files/4846914/reproducibility.zip)

**Comment by ahartikainen** [comment]
Hi, see the link

https://mc-stan.org/docs/2_23/reference-manual/reproducibility-chapter.html

**Comment by MaxRCohen** [comment]
Hi, 

Thank you for the helpful link! So it seems that PyStan will be unable to reproduce the exact same sampling outputs on different machines. Is that correct?

As a tangent, do you know if this is something inherent to all Bayesian inference software?

Thank you for the help!

**Comment by betanalpha** [comment]
This is inherent to any software that uses floating point arithmetic in languages 
like C++ where the language spec doesn’t not fully specify how floating point 
arithmetic has to be implemented.  This includes the Stan core libraries and 
hence all of the Stan interfaces.  

The Markov chain Monte Carlo methods used by Stan, however, amplify these
variations so that the realized Markov chains are not just slightly different.  
Essentially the variations in how floating point arithmetic is implemented is 
like running with a different pseudo-random number generator seed.

**Comment by MaxRCohen** [comment]
Thank you for the detailed explanation. I think I fully understand what to expect now.

**Comment by bob-carpenter** [comment]
For more info, see the Stan reference manual [chapter on reproducibility](https://mc-stan.org/docs/2_23/reference-manual/reproducibility-chapter.html).  You also need to be using the same OS version, the same compiler with the same flags.  Just about anything can disturb floating point reproducibility.

What should work, though, is replication.  Running Stan on different machines should give you the same answer up to MCMC sampling error in cases where you don't run into a precision issue on one setup that doesn't arise in the other.
