### ISSUE TITLE
Can't Use Pystan on Windows Server, With python (3.7.3) and PiP (20.1.1)

### ISSUE THREAD

**Issue by Oradim** [stan-dev/pystan2#715]
When I try to use Pystan(Version 2.19.1.1)  with PyCharm.
I always get the following Error:
ImportError: DLL not found.

I tried to reinstall pystan, I tried to reinstall all requirements.
I created new environments and reinstalled everthing.

I found that some people say that this is an issue with the windows version pystan.

Does anybody know what I could to make it work?

**Comment by ahartikainen** [comment]
Have you followed our Windows instructions?

https://pystan.readthedocs.io/en/latest/windows.html

**Comment by Oradim** [comment]
Hello ahartikainen,
I installed everything with pip install and not with conda.
I don't think that should solve the problem or do you think that would work?

**Comment by ahartikainen** [comment]
You need mingw-w64 compiler from conda.
