### ISSUE TITLE
How does constant behave in vb initialization? 

### ISSUE THREAD

**Issue by lliutianc** [stan-dev/pystan2#722]
#### Summary:

Hi, I am pretty new in PyStan so this issue may be silly and I might make something wrong..

I was trying to define a mixture model in PyStan where I encountered this strange issue: after including a constant 1.0(or just 1) to an inverse_logit value, the vb will fail to initialize and raise error about log(0).

#### Description:
Here is my model: 

```python

model_code = """
data {
    int<lower=1> N;
    int<lower=1> J;
    int<lower=1> K;
    int<lower=0, upper=1> Y[N, J];
}

parameters {
    vector[K] theta[N];
    matrix<lower=0>[J, K] A;
    vector[J] b;
}

transformed parameters {
    vector<lower=0, upper=1>[J] w_prob[N];
    vector[J] w_probs[N];
   
    for (n in 1:N){
        w_prob[n] = inv_logit(A * theta[n] + b);
        w_probs[n] = w_prob[n] * 1.0;
    }
}

model {
    for (j in 1:J){
        A[j] ~ lognormal(0, 5);
    }
    b ~ normal(0, 3);

    for (n in 1:N){
      // prior
        theta[n] ~ normal(0, 1);
        
      // likelihood
      for (j in 1:J){
          Y[n][j] ~ bernoulli(w_prob[n][j]);  // this could work
          Y[n][j] ~ bernoulli(w_probs[n][j]);  // this couldn't work
      }
    }
}
"""
```
I created two transformed variables: w_prob and w_probs, however, the vb will fail on the latter. If I change `w_probs[n] = w_prob[n] * 0.9999999999`, then both could work.

This is a tiny demo to reproduce the issue, I need to do something like `Y[n][j] ~ bernoulli(w_prob[n][j] * (1 - alpha[j]) + alpha[j])` in my application, but the same issue would occur: using `1` will lead to the failure, whereas using `0.999999999` will not.

I need to figure out how to include this `1`, And my assumption is that this would be floating number issue and reproduce the same error with this smaller model succefully.

#### Reproducible Steps:
My `Y` are binary data. All other details are listed above.

#### Current Output:

Error from the terminal
```bash
...
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
Rejecting initial value:
...
```

Error in Jupyter Notebook
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-cb3ec629d534> in <module>
----> 1 test = mirt.vb(data_dict)

~/miniconda3/lib/python3.7/site-packages/pystan/model.py in vb(self, data, pars, iter, seed, init, sample_file, diagnostic_file, verbose, algorithm, **kwargs)
   1005         stan_args = pystan.misc._get_valid_stan_args(stan_args)
   1006 
-> 1007         ret, sample = fit._call_sampler(stan_args, pars_oi=pars)
   1008 
   1009         logger.warning('Automatic Differentiation Variational Inference (ADVI) is an EXPERIMENTAL ALGORITHM.')

stanfit4anon_model_3a6765c9d4c0782e1fee7d88088ed01d_3171018489683927843.pyx in stanfit4anon_model_3a6765c9d4c0782e1fee7d88088ed01d_3171018489683927843.StanFit4Model._call_sampler()

stanfit4anon_model_3a6765c9d4c0782e1fee7d88088ed01d_3171018489683927843.pyx in stanfit4anon_model_3a6765c9d4c0782e1fee7d88088ed01d_3171018489683927843._call_sampler()

RuntimeError: stan::variational::advi::adapt_eta: Cannot compute ELBO using the initial variational distribution. Your model may be either severely ill-conditioned or misspecified.
```

#### Expected Output:
A runnable program.

#### PyStan Version:
2.19.1.1 via `print(pystan.__version__)`

#### Python Version:
3.7.7 via `print(sys.__version__)`

#### Operating System:
MacOS Catalina 10.15.6
```python
import os
import platform
print(os.name)
print(platform.system())
print(platform.release())
posix
Darwin
19.6.0
```

Thanks in advance!

**Comment by ahartikainen** [comment]
Does this work

model_code = """
data {
    int<lower=1> N;
    int<lower=1> J;
    int<lower=1> K;
    int<lower=0, upper=1> Y[N, J];
}

parameters {
    vector[K] theta[N];
    matrix<lower=0>[J, K] A;
    vector[J] b;
}

transformed parameters {
    vector<lower=0, upper=1>[J] w_prob[N];
   
    for (n in 1:N){
        w_prob[n] = inv_logit(A * theta[n] + b) * 1.0;
    }
}

model {
    for (j in 1:J){
        A[j] ~ lognormal(0, 5);
    }
    b ~ normal(0, 3);

    for (n in 1:N){
      // prior
        theta[n] ~ normal(0, 1);
        
      // likelihood
      for (j in 1:J){
          Y[n][j] ~ bernoulli(w_prob[n][j]);  // this could work
      }
    }
}
"""

I think there could be some problems when you have "duplicate" data. I could be wrong.
