### ISSUE TITLE
Remove python 2.7 support

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan2#738]
Do/Did we drop the python 2 compatability with this repo?

**Comment by riddell-stan** [comment]
Right now my thinking is that we would not have a new release of pystan 2. PyStan 3 seems like it should be stable on Linux and macOS in a month or so.

**Comment by ahartikainen** [comment]
Yeah, that is ok.

Tests are failing, because python 2.7 is missing the new method.
