### ISSUE TITLE
Pystan from docker with conda? 

### ISSUE THREAD

**Issue by elbamos** [stan-dev/pystan2#742]
#### Summary:
I'm trying to build a docker image that runs pystan, and getting the often-reported `distutils.errors.CompileError: command 'gcc' failed with exit status 1` compilation error. 

I'm asking for advice and/or a recipe. 

#### Description:
I'm trying to build a docker image that runs pystan.  I've tried a variety of compiler options and python versions, following the other git issues created regarding this error.  I'm looking for advice and/or a recipe. 

#### Reproducible Steps:
The environment is created by the following Dockerfile:

```
FROM continuumio/miniconda:latest
RUN conda update -y conda
RUN conda install -y python=3.6 pandas pyarrow pystan=2.19
```

I then attempt to compile a simple model with pystan.

#### Current Output:

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_ae63a2423d889674391f31335cae5778 NOW.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/conda/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/conda/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

#### Expected Output:
I expect the model to compile into a pystan StanModel object that can be used for inference. 

#### PyStan Version:
2.19.1

#### Python Version:
I've tried 3.6 and 3.7

#### Operating System:
I'm doing this from MacOS, but the use of docker and conda should neutralize the OS issue.  (The goal is a docker that I will then be able to deploy into an unknown-OS environment.)

**Comment by ahartikainen** [comment]
Have you tried https://github.com/arviz-devs/arviz/blob/master/scripts/Dockerfile

```
FROM conda/miniconda3

# Update container
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Install PyStan
RUN conda update conda
RUN conda update setuptools

RUN pip install numpy cython
RUN pip install pystan

# Remove conda cache
RUN conda clean --all
```

I'm sure `conda install pystan -c conda-forge` works too. You just need `build-essential`.

**Comment by elbamos** [comment]
Thanks!  Adding `RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*` did it. FYI `pystan` is now in the default conda repository.
