### ISSUE TITLE
Failed to build pystan

### ISSUE THREAD

**Issue by kewp** [stan-dev/pystan2#744]
#### Summary:
 Cannot build pystan on arch linux

#### Description:

I'm running `pip3 install pystan` and it failed. Huge error message. Cannot figure out what the root cause is.

I've uploaded the log file of the installation. See below.

#### Current Output:

(I think this log might have been from `pip3 install fbprophet` but I was getting the same error with the above command).

[pip.log](https://github.com/stan-dev/pystan/files/5872573/pip.log)

#### Python Version:

3.9.1

#### Operating System:

Linux localhost 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux

I've done a full update (`pacman -Syyu`)

#### GCC

I should note my system has GCC 10.2.0

**Comment by ahartikainen** [comment]
At the first glance, I have no idea why is that failing.
Can you try to install wheel first and then trying pip install again.

**Comment by kewp** [comment]
I have tried that. Didn't help

**Comment by ahartikainen** [comment]
Ok,

Then one thing is to try

    pip install -vvvv pystan

I think there have been similar problems previously too. (Something to do with C++14 compatibility?). Maybe we can reproduce this with a docker.

**Comment by kewp** [comment]
Here is the log.

[pip.log](https://github.com/stan-dev/pystan/files/5874492/pip.log)
