### ISSUE TITLE
Importing pystan makes logging level very noisy

### ISSUE THREAD

**Issue by canyon289** [stan-dev/pystan2#745]
#### Summary:
For some reason importing pystan makes the logging level very noisy for some reason. See Matplotlib logging output between the two cases
![image](https://user-images.githubusercontent.com/7213793/106225493-19c30080-619a-11eb-90d6-53f048c720c7.png)

#### Description:
See above

#### Reproducible Steps:
```
import matplotlib
import sys
import matplotlib.pyplot as plt
matplotlib.__version__

fig, ax = plt.subplots()
ax.set_yticklabels([f"$\\mathcal{{N}}$" for i in range(2)], fontsize=16);

import pystan
pystan.__version__
fig, ax = plt.subplots()
ax.set_yticklabels([f"$\\mathcal{{N}}$" for i in range(2)], fontsize=16);
```

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### PyStan Version:
'2.19.1.1'
#### Python Version:
3.9.1
#### Operating System:
Ubuntu 20.04

Extra info,
Heres what it looks like in bigger notebook

# When Pystan is imported
![image](https://user-images.githubusercontent.com/7213793/106225641-6e667b80-619a-11eb-9b98-f00989b650cb.png)

# Without pystan import 
![image](https://user-images.githubusercontent.com/7213793/106225704-905ffe00-619a-11eb-9d18-630a0de8a4e0.png)

**Comment by ahartikainen** [comment]
Is this some macos / jupyter specific problem?

What happens if you import pystan at start?

Also see https://pystan.readthedocs.io/en/latest/logging.html

**Comment by canyon289** [comment]
Im on linux, it might be jupyter specific though.

If I import pystan then the logging becomes very verbose for both code blocks

**Comment by canyon289** [comment]
Also feel free to treat this as low priority and I can come fix later after I finish writing the book chapters
