### ISSUE TITLE
Failing to build on MacOSX 10.15.7 Catalina

### ISSUE THREAD

**Issue by cmgoold** [stan-dev/pystan2#747]
#### Summary:
Running `python3 -m pip install pystan` results in numerous error messages and failure to build on new Mac OSX running Catalina 10.15.7. 

#### Description:
For what I can see, the main error is:

```
  ERROR: Failed building wheel for pystan
  Running setup.py clean for pystan
Failed to build pystan
Installing collected packages: pystan
    Running setup.py install for pystan ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7w/865y75kn6739v3ynt32w9tsm0000gn/T/pip-install-hy7np2go/pystan_18eba381bd574e5aa59fda912ed55c23/setup.py'"'"'; __file__='"'"'/private/var/folders/7w/865y75kn6739v3ynt32w9tsm0000gn/T/pip-install-hy7np2go/pystan_18eba381bd574e5aa59fda912ed55c23/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7w/865y75kn6739v3ynt32w9tsm0000gn/T/pip-record-5mnbrvmw/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/pystan
         cwd: /private/var/folders/7w/865y75kn6739v3ynt32w9tsm0000gn/T/pip-install-hy7np2go/pystan_18eba381bd574e5aa59fda912ed55c23/
```
Then there is over 20,000 lines of output. The first error arises after numerous copying statements saying:

```
running build_ext
building 'pystan._api' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g
```

Then I get a bunch of `error: unknown type name '__uint64_t'` and `error: unknown type name '__uint32_t'; did you mean '__uint128_t'?` messages, followed by a bunch of `error architecture not supported` errors, e.g.:

```
error architecture not supportedIn file included from pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp:1
```

#### Reproducible Steps:
This is a 2020 Apple MacBook Pro with Catalina 10.15.7. I haven't installed much before trying to install `pystan`. My `pip freeze` looks like:

```
appdirs==1.4.4
attrs==20.3.0
certifi==2020.12.5
cfgv==3.2.0
cftime==1.3.1
click==7.1.2
cmdstanpy==0.9.67
cycler==0.10.0
Cython==0.29.21
dill==0.3.3
distlib==0.3.1
filelock==3.0.12
h11==0.12.0
identify==1.5.13
iniconfig==1.1.1
kiwisolver==1.3.1
matplotlib==3.3.2
multiprocess==0.70.11.1
netCDF4==1.5.5.1
nodeenv==1.5.0
numpy==1.19.5
packaging==20.8
pandas==1.2.1
Pillow==8.1.0
pluggy==0.13.1
pox==0.2.9
ppft==1.6.6.3
psycopg2==2.8.6
py==1.10.0
pydantic==1.7.3
pyparsing==2.4.7
pytest==6.2.2
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.4.1
scipy==1.6.0
seaborn==0.11.1
six==1.15.0
starlette==0.13.6
toml==0.10.2
toolz==0.11.1
typing-extensions==3.7.4.3
uvicorn==0.13.3
virtualenv==20.4.0
xarray==0.16.2
```

#### Current Output:
See above. 

#### Expected Output:
Successfully installing `pystan`

#### PyStan Version:
2.19.1.1

#### Python Version:
3.9.1

#### Operating System:
Mac OSX, Catalina 10.15.7

**Comment by ahartikainen** [comment]
Hi what compiler do you have?

    gcc --version


Can you install with the following

    pip install -vvvv pystan > pip.log

And then either copy pip.log here or search for C++ errors.

**Comment by cmgoold** [comment]
The pip log is attached. [pip.log](https://github.com/stan-dev/pystan2/files/5917078/pip.log)

The output of `gcc --version` version is:

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

As I understand it, Clang links to G++ and it has been that way for a while?

**Comment by ahartikainen** [comment]
It might be the same problem everyone else has with macOS

https://apple.stackexchange.com/questions/372032/usr-include-missing-on-macos-catalina-with-xcode-11

Maybe try

    export CPATH=`xcrun --show-sdk-path`/usr/include

and try again

**Comment by cmgoold** [comment]
Unfortunately, this didn't work. Here's the log:
[pip.log](https://github.com/stan-dev/pystan2/files/5919332/pip.log)
