### ISSUE TITLE
Pystan Windows 10 non-Anaconda 

### ISSUE THREAD

**Issue by DP92675** [stan-dev/pystan2#755]
Is there any plan to provide support for non-Anaconda python environments? This seems to be an issue for many users.

**Comment by ahartikainen** [comment]
Currently there are no plans to go back MSVC toolchain, and clang-cl is missing support from python, which makes things hard.

**Comment by bbbales2** [comment]
Does cmdstanpy work here?

**Comment by ahartikainen** [comment]
Yes, CmdStanPy works.
