### ISSUE TITLE
Getting pystan working on Windows

### ISSUE THREAD

**Issue by patricksnape** [stan-dev/pystan2#77]
## Overview

So I've managed to get pystan working on Windows (#24). 

![pystan_windows](https://cloud.githubusercontent.com/assets/708474/2831450/2af5044a-cfb9-11e3-899f-795f0909ad0e.png)

Unfortunately, it requires a few different changes to both pystan AND stan. It also requires you to download, install and set up Visual Studio 2008 (for Python 2.7 at least). The instructions on how to do this are [here](https://github.com/menpo/menpo/wiki/Development:-Setting-up-a-Windows-development-environment).

I have also uploaded a binary conda package to binstar which lives [here](https://binstar.org/patricksnape/pystan). In order to install this, download and install miniconda and then open up a prompt and type:

```
conda install -c patricksnape pystan
```

Which should download and install pystan and it's dependancies. It should be noted that multiprocessing is complicated on Windows, and so you **have to set `n_jobs=0`** otherwise you will get in to an infinite loop. 
## Fixes to be made

At the moment [my conda build script](https://github.com/menpo/conda-recipes/tree/master/pystan) patches the pystan 2.2.0.0 from pypi in order to allow compilation using Visual Studio. The changes are summarised as:
- In `setup.py` you require two different compile flags on windows
  - `/EHsc` - required to turn exceptions on for boost
  - `-DBOOST_DATE_TIME_NO_LIB` - a bug linking boost on Windows
- Those two flags also have been turned on in `model.py`
- In `stan_fit.hpp` you have to cast the integer passed in to `log10`
  - Visual Studio has a different `cmath` header which defines multiple definitions of most functions. Therefore, when it goes to cast the integer, it doesn't know what to cast it to and so throws an 'ambiguous' error. Therefore, this is easily fixed by just casting the integer to double when it is passed in:
  - `int it_print_width = std::ceil(std::log10((double)finish));`
## Changes in Stan

Go [here](https://github.com/stan-dev/stan/issues/632) to see the changes required to stan for building in Visual Studio.

**Comment by icoxfog417** [comment]
Thank you for nice package. But [patricksnape / pystan](https://binstar.org/patricksnape/pystan/files) only supports version 2.5. 

If we want to use latest version (2.7), do we have to compile source on Windows ([it is not supported](http://pystan.readthedocs.org/en/latest/windows.html#windows))?

**Comment by ariddell** [comment]
Thanks for the note. I'll ask @patricksnape if he wouldn't mind creating a fresh package for 2.7. I've created a new issue to track this, #164

**Comment by ariddell** [comment]
@icoxfog417 PyStan 2.7 should be available on conda now.

**Comment by icoxfog417** [comment]
@ariddell @patricksnape , Thank you for quick support! I appreciate your help.
