### ISSUE TITLE
temporary files garbage collection

### ISSUE THREAD

**Issue by karlnapf** [stan-dev/pystan2#99]
Hi Alan,

I am using pystan on a cluster computer, running thousands of instances on small samples sizes with a large intended throughput. Now I found out that I killed the cluster FS since pystan is creating all these temporary directories to store its library files. I checked the code and indeed the constructor of `StanModel` creates a temp files and then puts a "pystan" in there and stores stuff.

I have to clean up those things after running the sampling. What do you think is the best way?
- Add a clean-up methods to StamModel?
- Add the possibility to pass an explicit path? Then I could delete myself, currently I cannot get the path
- other ideas?

Thanks!
H

PS. Pystan is great!

**Comment by jbao** [comment]
hmm, it seems I have exactly the same problem with the latest release when running stan jobs in parallel on a cluster. From what I understood, the `__del__` method in the `StanModel` class has also been replaced by `shutil.rmtree` in the constructor, which I assume does the same thing, but not sure whether this has an impact.
